/* Generated By:JavaCC: Do not edit this line. expressionGrammarConstants.java */
package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.service.expressionGrammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface expressionGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int QUOTED = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<WORD>",
    "<AND>",
    "<OR>",
    "\"!\"",
    "<QUOTED>",
    "\"(\"",
    "\")\"",
  };

}
