/* Generated By:JavaCC: Do not edit this line. expressionGrammar.java */
package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.service.expressionGrammar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.silicolife.textmining.core.interfaces.core.document.ISearchProperties;
import java.util.ArrayList;
import org.apache.lucene.search.Query;
import org.hibernate.search.query.dsl.QueryBuilder;
import com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.dao.GenericLuceneDaoImpl;
import com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.dao.IGenericLuceneDao;



public class expressionGrammar<T> implements expressionGrammarConstants {

  private  List<String> fields;

  private  QueryBuilder qb;

  private IGenericLuceneDao<T> genericDao;

    public List<String> getFields() {
        return fields;
        }
        public void setFields(List<String> fields) {
                this.fields = fields;
        }
        public QueryBuilder getQb() {
                return qb;
        }
        public void setQb(QueryBuilder qb) {
                this.qb = qb;
        }
        public IGenericLuceneDao<T> getGenericDao() {
                return genericDao;
        }
        public void setGenericDao(IGenericLuceneDao<T> genericDao) {
                this.genericDao = genericDao;
        }

  public Query parseExpression() throws ParseException
  {
    //expressionGrammar parser = new expressionGrammar(System.in);
    //List<String> fields = new ArrayList<String >();
    //fields.add("title");
    //fields.add("full text");
    //this.fields = fields;        Query result = null;
      try
      {
         result = this.one_line();
        //System.out.println("OK");
      }
      catch (Exception e)
      {
       // System.out.println("NOK.");
       // System.out.println(e.getMessage());
        this.ReInit(System.in);
      }
      catch (Error e)
      {
        //System.out.println("Oops.");
        //System.out.println(e.getMessage());

      }
      return result;
    }


        public  Map<String, String> putOnEqSentenceOnField(String value){
                Map<String, String> eqSentenceOnField = new HashMap<String, String>();
                for(String field : this.fields){
                        eqSentenceOnField.put(field, value);
                }
                return eqSentenceOnField;
        }

  final public Query one_line() throws ParseException {
 ArrayList<Query> queriesOut = new ArrayList<Query>();
    operation(queriesOut);
    //System.out.println(queriesOut.size());
    {if (true) return queriesOut.get(0);}
    throw new Error("Missing return statement in function");
  }

  final public void andOp(ArrayList<Query> queriesIn) throws ParseException {
 ArrayList<Query> queriesOut = new ArrayList<Query>();
    jj_consume_token(12);
    jj_consume_token(13);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUOTED:
      case 12:
      case 15:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      t(queriesOut);
    }
    jj_consume_token(14);
          //System.out.println("AND");
          queriesIn.add(this.genericDao.createMustQuery(queriesOut, this.qb));
  }

  final public void orOp(ArrayList<Query> queriesIn) throws ParseException {
  ArrayList<Query> queriesOut = new ArrayList<Query>();
    jj_consume_token(15);
    jj_consume_token(13);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUOTED:
      case 12:
      case 15:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      t(queriesOut);
    }
    jj_consume_token(14);
          //System.out.println("OR");
          queriesIn.add(this.genericDao.createShouldQuery(queriesOut, this.qb));
  }

  final public void operation(ArrayList<Query> queriesIn) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 12:
      andOp(queriesIn);
      break;
    case 15:
      orOp(queriesIn);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void t(ArrayList<Query> queriesIn) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 12:
    case 15:
      operation(queriesIn);
      break;
    case QUOTED:
      phrase(queriesIn);
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void phrase(ArrayList<Query> queriesIn) throws ParseException {
  Token phrase;
Map<String, String> eqSentenceOnField = null;
    phrase = jj_consume_token(QUOTED);
          //System.out.println(phrase.toString().replace("\"",""));
          //System.out.println(this.putOnEqSentenceOnField(phrase.toString().replace("\"","")).toString());
          eqSentenceOnField = this.putOnEqSentenceOnField(phrase.toString().replace("\u005c"",""));
          queriesIn.add(this.genericDao.createShouldPhraseQuery(eqSentenceOnField, this.qb));
  }

  final public void sum() throws ParseException {
    term();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      term();
    }
  }

  final public void term() throws ParseException {
    unary();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
      case DIVIDE:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
        jj_consume_token(MULTIPLY);
        break;
      case DIVIDE:
        jj_consume_token(DIVIDE);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      unary();
    }
  }

  final public void unary() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      jj_consume_token(MINUS);
      element();
      break;
    case CONSTANT:
    case 16:
      element();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void element() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTANT:
      jj_consume_token(CONSTANT);
      break;
    case 16:
      jj_consume_token(16);
      sum();
      jj_consume_token(17);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /** Generated Token Manager. */
  public expressionGrammarTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[10];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x9800,0x9800,0x9000,0x9800,0x60,0x60,0x180,0x180,0x10240,0x10200,};
   }

  /** Constructor with InputStream. */
  public expressionGrammar(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public expressionGrammar(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new expressionGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public expressionGrammar(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new expressionGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public expressionGrammar(expressionGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(expressionGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[18];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 10; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 18; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
