package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AnnotationLogs generated by hbm2java
 */
@Entity
@Table(name = "annotation_logs")
public class AnnotationLogs implements java.io.Serializable {

	private AnnotationLogsId id;
	private Annotations annotations;
	private AuthUsers authUsers;
	private Corpus corpus;
	private Processes processes;
	private Publications publications;
	private String aloAnnotLogType;
	private String aloAnnotOld;
	private String aloAnnotNew;
	private String aloNotes;
	private Date aloDate;

	public AnnotationLogs() {
	}

	public AnnotationLogs(AnnotationLogsId id, AuthUsers authUsers, Corpus corpus, Processes processes, Publications publications, String aloAnnotLogType, String aloAnnotOld,
			String aloAnnotNew, Date aloDate) {
		this.id = id;
		this.authUsers = authUsers;
		this.corpus = corpus;
		this.processes = processes;
		this.publications = publications;
		this.aloAnnotLogType = aloAnnotLogType;
		this.aloAnnotOld = aloAnnotOld;
		this.aloAnnotNew = aloAnnotNew;
		this.aloDate = aloDate;
	}

	public AnnotationLogs(AnnotationLogsId id, Annotations annotations, AuthUsers authUsers, Corpus corpus, Processes processes, Publications publications, String aloAnnotLogType,
			String aloAnnotOld, String aloAnnotNew, String aloNotes, Date aloDate) {
		this.id = id;
		this.annotations = annotations;
		this.authUsers = authUsers;
		this.corpus = corpus;
		this.processes = processes;
		this.publications = publications;
		this.aloAnnotLogType = aloAnnotLogType;
		this.aloAnnotOld = aloAnnotOld;
		this.aloAnnotNew = aloAnnotNew;
		this.aloNotes = aloNotes;
		this.aloDate = aloDate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "aloId", column = @Column(name = "alo_id", nullable = false)),
			@AttributeOverride(name = "aloUserId", column = @Column(name = "alo_user_id", nullable = false)) })
	public AnnotationLogsId getId() {
		return this.id;
	}

	public void setId(AnnotationLogsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alo_annotation_id")
	public Annotations getAnnotations() {
		return this.annotations;
	}

	public void setAnnotations(Annotations annotations) {
		this.annotations = annotations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alo_user_id", nullable = false, insertable = false, updatable = false)
	public AuthUsers getAuthUsers() {
		return this.authUsers;
	}

	public void setAuthUsers(AuthUsers authUsers) {
		this.authUsers = authUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alo_corpus_id", nullable = false)
	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alo_process_id", nullable = false)
	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "alo_publication_id", nullable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	@Column(name = "alo_annot_log_type", nullable = false, length = 14)
	public String getAloAnnotLogType() {
		return this.aloAnnotLogType;
	}

	public void setAloAnnotLogType(String aloAnnotLogType) {
		this.aloAnnotLogType = aloAnnotLogType;
	}

	@Column(name = "alo_annot_old", nullable = false, length = 300)
	public String getAloAnnotOld() {
		return this.aloAnnotOld;
	}

	public void setAloAnnotOld(String aloAnnotOld) {
		this.aloAnnotOld = aloAnnotOld;
	}

	@Column(name = "alo_annot_new", nullable = false, length = 300)
	public String getAloAnnotNew() {
		return this.aloAnnotNew;
	}

	public void setAloAnnotNew(String aloAnnotNew) {
		this.aloAnnotNew = aloAnnotNew;
	}

	@Column(name = "alo_notes", length = 65535)
	public String getAloNotes() {
		return this.aloNotes;
	}

	public void setAloNotes(String aloNotes) {
		this.aloNotes = aloNotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "alo_date", nullable = false, length = 19)
	public Date getAloDate() {
		return this.aloDate;
	}

	public void setAloDate(Date aloDate) {
		this.aloDate = aloDate;
	}

}
