package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnnotationPropertiesId generated by hbm2java
 */
@Embeddable
public class AnnotationPropertiesId implements java.io.Serializable {

	private String anpPropKey;
	private long anpId;

	public AnnotationPropertiesId() {
	}

	public AnnotationPropertiesId(String anpPropKey, long anpId) {
		this.anpPropKey = anpPropKey;
		this.anpId = anpId;
	}

	@Column(name = "anp_prop_key", nullable = false)
	public String getAnpPropKey() {
		return this.anpPropKey;
	}

	public void setAnpPropKey(String anpPropKey) {
		this.anpPropKey = anpPropKey;
	}

	@Column(name = "anp_id", nullable = false)
	public long getAnpId() {
		return this.anpId;
	}

	public void setAnpId(long anpId) {
		this.anpId = anpId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnnotationPropertiesId))
			return false;
		AnnotationPropertiesId castOther = (AnnotationPropertiesId) other;

		return ((this.getAnpPropKey() == castOther.getAnpPropKey()) || (this.getAnpPropKey() != null && castOther.getAnpPropKey() != null && this.getAnpPropKey().equals(
				castOther.getAnpPropKey())))
				&& (this.getAnpId() == castOther.getAnpId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAnpPropKey() == null ? 0 : this.getAnpPropKey().hashCode());
		result = 37 * result + (int) this.getAnpId();
		return result;
	}

}
