package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnnotationSidesId generated by hbm2java
 */
@Embeddable
public class AnnotationSidesId implements java.io.Serializable {

	private long asAnnotationId;
	private long asAnnotationSubId;

	public AnnotationSidesId() {
	}

	public AnnotationSidesId(long asAnnotationId, long asAnnotationSubId) {
		this.asAnnotationId = asAnnotationId;
		this.asAnnotationSubId = asAnnotationSubId;
	}

	@Column(name = "as_annotation_id", nullable = false)
	public long getAsAnnotationId() {
		return this.asAnnotationId;
	}

	public void setAsAnnotationId(long asAnnotationId) {
		this.asAnnotationId = asAnnotationId;
	}

	@Column(name = "as_annotation_sub_id", nullable = false)
	public long getAsAnnotationSubId() {
		return this.asAnnotationSubId;
	}

	public void setAsAnnotationSubId(long asAnnotationSubId) {
		this.asAnnotationSubId = asAnnotationSubId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnnotationSidesId))
			return false;
		AnnotationSidesId castOther = (AnnotationSidesId) other;

		return (this.getAsAnnotationId() == castOther.getAsAnnotationId()) && (this.getAsAnnotationSubId() == castOther.getAsAnnotationSubId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAsAnnotationId();
		result = 37 * result + (int) this.getAsAnnotationSubId();
		return result;
	}

}
