package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthGroupHasRolesId generated by hbm2java
 */
@Embeddable
public class AuthGroupHasRolesId implements java.io.Serializable {

	private long agrGroupId;
	private long agrRoleId;

	public AuthGroupHasRolesId() {
	}

	public AuthGroupHasRolesId(long agrGroupId, long agrRoleId) {
		this.agrGroupId = agrGroupId;
		this.agrRoleId = agrRoleId;
	}

	@Column(name = "agr_group_id", nullable = false)
	public long getAgrGroupId() {
		return this.agrGroupId;
	}

	public void setAgrGroupId(long agrGroupId) {
		this.agrGroupId = agrGroupId;
	}

	@Column(name = "agr_role_id", nullable = false)
	public long getAgrRoleId() {
		return this.agrRoleId;
	}

	public void setAgrRoleId(long agrRoleId) {
		this.agrRoleId = agrRoleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthGroupHasRolesId))
			return false;
		AuthGroupHasRolesId castOther = (AuthGroupHasRolesId) other;

		return (this.getAgrGroupId() == castOther.getAgrGroupId()) && (this.getAgrRoleId() == castOther.getAgrRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAgrGroupId();
		result = 37 * result + (int) this.getAgrRoleId();
		return result;
	}

}
