package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthUserSettingsId generated by hbm2java
 */
@Embeddable
public class AuthUserSettingsId implements java.io.Serializable {

	private long ausUserId;
	private String ausPropKey;

	public AuthUserSettingsId() {
	}

	public AuthUserSettingsId(long ausUserId, String ausPropKey) {
		this.ausUserId = ausUserId;
		this.ausPropKey = ausPropKey;
	}

	@Column(name = "aus_user_id", nullable = false)
	public long getAusUserId() {
		return this.ausUserId;
	}

	public void setAusUserId(long ausUserId) {
		this.ausUserId = ausUserId;
	}

	@Column(name = "aus_prop_key", nullable = false)
	public String getAusPropKey() {
		return this.ausPropKey;
	}

	public void setAusPropKey(String ausPropKey) {
		this.ausPropKey = ausPropKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthUserSettingsId))
			return false;
		AuthUserSettingsId castOther = (AuthUserSettingsId) other;

		return (this.getAusUserId() == castOther.getAusUserId())
				&& ((this.getAusPropKey() == castOther.getAusPropKey()) || (this.getAusPropKey() != null && castOther.getAusPropKey() != null && this.getAusPropKey().equals(
						castOther.getAusPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAusUserId();
		result = 37 * result + (getAusPropKey() == null ? 0 : this.getAusPropKey().hashCode());
		return result;
	}

}
