package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuthUserLogs generated by hbm2java
 */
@Entity
@Table(name = "auth_user_logs")
public class AuthUserLogs implements java.io.Serializable {

	private Long aulId;
	private AuthUsers authUsers;
	private Date aulCreateDate;
	private String aulOperation;
	private String aulTableChanged;
	private String aulSqlCommand;
	private String aulNotes;

	public AuthUserLogs() {
	}

	public AuthUserLogs(AuthUsers authUsers, Date aulCreateDate, String aulOperation, String aulTableChanged) {
		this.authUsers = authUsers;
		this.aulCreateDate = aulCreateDate;
		this.aulOperation = aulOperation;
		this.aulTableChanged = aulTableChanged;
	}

	public AuthUserLogs(AuthUsers authUsers, Date aulCreateDate, String aulOperation, String aulTableChanged, String aulSqlCommand, String aulNotes) {
		this.authUsers = authUsers;
		this.aulCreateDate = aulCreateDate;
		this.aulOperation = aulOperation;
		this.aulTableChanged = aulTableChanged;
		this.aulSqlCommand = aulSqlCommand;
		this.aulNotes = aulNotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "aul_id", unique = true, nullable = false)
	public Long getAulId() {
		return this.aulId;
	}

	public void setAulId(Long aulId) {
		this.aulId = aulId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aul_user_id", nullable = false)
	public AuthUsers getAuthUsers() {
		return this.authUsers;
	}

	public void setAuthUsers(AuthUsers authUsers) {
		this.authUsers = authUsers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "aul_create_date", nullable = false, length = 19)
	public Date getAulCreateDate() {
		return this.aulCreateDate;
	}

	public void setAulCreateDate(Date aulCreateDate) {
		this.aulCreateDate = aulCreateDate;
	}

	@Column(name = "aul_operation", nullable = false, length = 7)
	public String getAulOperation() {
		return this.aulOperation;
	}

	public void setAulOperation(String aulOperation) {
		this.aulOperation = aulOperation;
	}

	@Column(name = "aul_table_changed", nullable = false, length = 128)
	public String getAulTableChanged() {
		return this.aulTableChanged;
	}

	public void setAulTableChanged(String aulTableChanged) {
		this.aulTableChanged = aulTableChanged;
	}

	@Column(name = "aul_sql_command", length = 16777215)
	public String getAulSqlCommand() {
		return this.aulSqlCommand;
	}

	public void setAulSqlCommand(String aulSqlCommand) {
		this.aulSqlCommand = aulSqlCommand;
	}

	@Column(name = "aul_notes", length = 16777215)
	public String getAulNotes() {
		return this.aulNotes;
	}

	public void setAulNotes(String aulNotes) {
		this.aulNotes = aulNotes;
	}

}
