package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassHierarchiesId generated by hbm2java
 */
@Embeddable
public class ClassHierarchiesId implements java.io.Serializable {

	private long clhClassId;
	private long clhSuperClassId;

	public ClassHierarchiesId() {
	}

	public ClassHierarchiesId(long clhClassId, long clhSuperClassId) {
		this.clhClassId = clhClassId;
		this.clhSuperClassId = clhSuperClassId;
	}

	@Column(name = "clh_class_id", nullable = false)
	public long getClhClassId() {
		return this.clhClassId;
	}

	public void setClhClassId(long clhClassId) {
		this.clhClassId = clhClassId;
	}

	@Column(name = "clh_super_class_id", nullable = false)
	public long getClhSuperClassId() {
		return this.clhSuperClassId;
	}

	public void setClhSuperClassId(long clhSuperClassId) {
		this.clhSuperClassId = clhSuperClassId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassHierarchiesId))
			return false;
		ClassHierarchiesId castOther = (ClassHierarchiesId) other;

		return (this.getClhClassId() == castOther.getClhClassId()) && (this.getClhSuperClassId() == castOther.getClhSuperClassId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClhClassId();
		result = 37 * result + (int) this.getClhSuperClassId();
		return result;
	}

}
