package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClassHierarchies generated by hbm2java
 */
@Entity
@Table(name = "class_hierarchies")
public class ClassHierarchies implements java.io.Serializable {

	private ClassHierarchiesId id;
	private Classes classesByClhSuperClassId;
	private Classes classesByClhClassId;

	public ClassHierarchies() {
	}

	public ClassHierarchies(ClassHierarchiesId id, Classes classesByClhSuperClassId, Classes classesByClhClassId) {
		this.id = id;
		this.classesByClhSuperClassId = classesByClhSuperClassId;
		this.classesByClhClassId = classesByClhClassId;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "clhClassId", column = @Column(name = "clh_class_id", nullable = false)),
			@AttributeOverride(name = "clhSuperClassId", column = @Column(name = "clh_super_class_id", nullable = false)) })
	public ClassHierarchiesId getId() {
		return this.id;
	}

	public void setId(ClassHierarchiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clh_super_class_id", nullable = false, insertable = false, updatable = false)
	public Classes getClassesByClhSuperClassId() {
		return this.classesByClhSuperClassId;
	}

	public void setClassesByClhSuperClassId(Classes classesByClhSuperClassId) {
		this.classesByClhSuperClassId = classesByClhSuperClassId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clh_class_id", nullable = false, insertable = false, updatable = false)
	public Classes getClassesByClhClassId() {
		return this.classesByClhClassId;
	}

	public void setClassesByClhClassId(Classes classesByClhClassId) {
		this.classesByClhClassId = classesByClhClassId;
	}

}
