package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes", uniqueConstraints = @UniqueConstraint(columnNames = "cla_name"))
public class Classes implements java.io.Serializable {

	private long claId;
	private String claName;
	private String claColor;
	private Set<Annotations> annotationses = new HashSet<Annotations>(0);
	private Set<ClassHierarchies> classHierarchiesesForClhSuperClassId = new HashSet<ClassHierarchies>(0);
	private Set<ClassHierarchies> classHierarchiesesForClhClassId = new HashSet<ClassHierarchies>(0);
	private Set<ResourceElements> resourceElementses = new HashSet<ResourceElements>(0);

	public Classes() {
	}

	public Classes(long claId, String claName) {
		this.claId = claId;
		this.claName = claName;
	}

	public Classes(long claId, String claName, String claColor, Set<Annotations> annotationses, Set<ClassHierarchies> classHierarchiesesForClhSuperClassId,
			Set<ClassHierarchies> classHierarchiesesForClhClassId, Set<ResourceElements> resourceElementses) {
		this.claId = claId;
		this.claName = claName;
		this.claColor = claColor;
		this.annotationses = annotationses;
		this.classHierarchiesesForClhSuperClassId = classHierarchiesesForClhSuperClassId;
		this.classHierarchiesesForClhClassId = classHierarchiesesForClhClassId;
		this.resourceElementses = resourceElementses;
	}

	@Id
	@Column(name = "cla_id", unique = true, nullable = false)
	public long getClaId() {
		return this.claId;
	}

	public void setClaId(long claId) {
		this.claId = claId;
	}

	@Column(name = "cla_name", unique = true, nullable = false)
	public String getClaName() {
		return this.claName;
	}

	public void setClaName(String claName) {
		this.claName = claName;
	}

	@Column(name = "cla_color", length = 10)
	public String getClaColor() {
		return this.claColor;
	}

	public void setClaColor(String claColor) {
		this.claColor = claColor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<Annotations> getAnnotationses() {
		return this.annotationses;
	}

	public void setAnnotationses(Set<Annotations> annotationses) {
		this.annotationses = annotationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classesByClhSuperClassId")
	public Set<ClassHierarchies> getClassHierarchiesesForClhSuperClassId() {
		return this.classHierarchiesesForClhSuperClassId;
	}

	public void setClassHierarchiesesForClhSuperClassId(Set<ClassHierarchies> classHierarchiesesForClhSuperClassId) {
		this.classHierarchiesesForClhSuperClassId = classHierarchiesesForClhSuperClassId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classesByClhClassId")
	public Set<ClassHierarchies> getClassHierarchiesesForClhClassId() {
		return this.classHierarchiesesForClhClassId;
	}

	public void setClassHierarchiesesForClhClassId(Set<ClassHierarchies> classHierarchiesesForClhClassId) {
		this.classHierarchiesesForClhClassId = classHierarchiesesForClhClassId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	public Set<ResourceElements> getResourceElementses() {
		return this.resourceElementses;
	}

	public void setResourceElementses(Set<ResourceElements> resourceElementses) {
		this.resourceElementses = resourceElementses;
	}

}
