package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClusterLabels generated by hbm2java
 */
@Entity
@Table(name = "cluster_labels")
public class ClusterLabels implements java.io.Serializable {

	private long cllClusterLabelId;
	private String cllClusterLabelName;
	private Double cllScore;
	private Set<ClusterProcessHasLabels> clusterProcessHasLabelses = new HashSet<ClusterProcessHasLabels>(0);
	private Set<ClusterLabelPublications> clusterLabelPublicationses = new HashSet<ClusterLabelPublications>(0);

	public ClusterLabels() {
	}

	public ClusterLabels(long cllClusterLabelId, String cllClusterLabelName) {
		this.cllClusterLabelId = cllClusterLabelId;
		this.cllClusterLabelName = cllClusterLabelName;
	}

	public ClusterLabels(long cllClusterLabelId, String cllClusterLabelName, Double cllScore, Set<ClusterProcessHasLabels> clusterProcessHasLabelses,
			Set<ClusterLabelPublications> clusterLabelPublicationses) {
		this.cllClusterLabelId = cllClusterLabelId;
		this.cllClusterLabelName = cllClusterLabelName;
		this.cllScore = cllScore;
		this.clusterProcessHasLabelses = clusterProcessHasLabelses;
		this.clusterLabelPublicationses = clusterLabelPublicationses;
	}

	@Id
	@Column(name = "cll_cluster_label_id", unique = true, nullable = false)
	public long getCllClusterLabelId() {
		return this.cllClusterLabelId;
	}

	public void setCllClusterLabelId(long cllClusterLabelId) {
		this.cllClusterLabelId = cllClusterLabelId;
	}

	@Column(name = "cll_cluster_label_name", nullable = false)
	public String getCllClusterLabelName() {
		return this.cllClusterLabelName;
	}

	public void setCllClusterLabelName(String cllClusterLabelName) {
		this.cllClusterLabelName = cllClusterLabelName;
	}

	@Column(name = "cll_score", precision = 22, scale = 0)
	public Double getCllScore() {
		return this.cllScore;
	}

	public void setCllScore(Double cllScore) {
		this.cllScore = cllScore;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clusterLabels")
	public Set<ClusterProcessHasLabels> getClusterProcessHasLabelses() {
		return this.clusterProcessHasLabelses;
	}

	public void setClusterProcessHasLabelses(Set<ClusterProcessHasLabels> clusterProcessHasLabelses) {
		this.clusterProcessHasLabelses = clusterProcessHasLabelses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clusterLabels")
	public Set<ClusterLabelPublications> getClusterLabelPublicationses() {
		return this.clusterLabelPublicationses;
	}

	public void setClusterLabelPublicationses(Set<ClusterLabelPublications> clusterLabelPublicationses) {
		this.clusterLabelPublicationses = clusterLabelPublicationses;
	}

}
