package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClusterLabelPublicationsId generated by hbm2java
 */
@Embeddable
public class ClusterLabelPublicationsId implements java.io.Serializable {

	private long clpClusterLabelId;
	private long clpQueryId;
	private long clpPublicationId;

	public ClusterLabelPublicationsId() {
	}

	public ClusterLabelPublicationsId(long clpClusterLabelId, long clpQueryId, long clpPublicationId) {
		this.clpClusterLabelId = clpClusterLabelId;
		this.clpQueryId = clpQueryId;
		this.clpPublicationId = clpPublicationId;
	}

	@Column(name = "clp_cluster_label_id", nullable = false)
	public long getClpClusterLabelId() {
		return this.clpClusterLabelId;
	}

	public void setClpClusterLabelId(long clpClusterLabelId) {
		this.clpClusterLabelId = clpClusterLabelId;
	}

	@Column(name = "clp_query_id", nullable = false)
	public long getClpQueryId() {
		return this.clpQueryId;
	}

	public void setClpQueryId(long clpQueryId) {
		this.clpQueryId = clpQueryId;
	}

	@Column(name = "clp_publication_id", nullable = false)
	public long getClpPublicationId() {
		return this.clpPublicationId;
	}

	public void setClpPublicationId(long clpPublicationId) {
		this.clpPublicationId = clpPublicationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClusterLabelPublicationsId))
			return false;
		ClusterLabelPublicationsId castOther = (ClusterLabelPublicationsId) other;

		return (this.getClpClusterLabelId() == castOther.getClpClusterLabelId()) && (this.getClpQueryId() == castOther.getClpQueryId())
				&& (this.getClpPublicationId() == castOther.getClpPublicationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClpClusterLabelId();
		result = 37 * result + (int) this.getClpQueryId();
		result = 37 * result + (int) this.getClpPublicationId();
		return result;
	}

}
