package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClusterPropertiesId generated by hbm2java
 */
@Embeddable
public class ClusterPropertiesId implements java.io.Serializable {

	private long clprClusterProcessId;
	private String clprPropKey;

	public ClusterPropertiesId() {
	}

	public ClusterPropertiesId(long clprClusterProcessId, String clprPropKey) {
		this.clprClusterProcessId = clprClusterProcessId;
		this.clprPropKey = clprPropKey;
	}

	@Column(name = "clpr_cluster_process_id", nullable = false)
	public long getClprClusterProcessId() {
		return this.clprClusterProcessId;
	}

	public void setClprClusterProcessId(long clprClusterProcessId) {
		this.clprClusterProcessId = clprClusterProcessId;
	}

	@Column(name = "clpr_prop_key", nullable = false)
	public String getClprPropKey() {
		return this.clprPropKey;
	}

	public void setClprPropKey(String clprPropKey) {
		this.clprPropKey = clprPropKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClusterPropertiesId))
			return false;
		ClusterPropertiesId castOther = (ClusterPropertiesId) other;

		return (this.getClprClusterProcessId() == castOther.getClprClusterProcessId())
				&& ((this.getClprPropKey() == castOther.getClprPropKey()) || (this.getClprPropKey() != null && castOther.getClprPropKey() != null && this.getClprPropKey().equals(
						castOther.getClprPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getClprClusterProcessId();
		result = 37 * result + (getClprPropKey() == null ? 0 : this.getClprPropKey().hashCode());
		return result;
	}

}
