package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClusterProcessHasLabelsId generated by hbm2java
 */
@Embeddable
public class ClusterProcessHasLabelsId implements java.io.Serializable {

	private long cphClusterProcessId;
	private long cphClusterLabelId;

	public ClusterProcessHasLabelsId() {
	}

	public ClusterProcessHasLabelsId(long cphClusterProcessId, long cphClusterLabelId) {
		this.cphClusterProcessId = cphClusterProcessId;
		this.cphClusterLabelId = cphClusterLabelId;
	}

	@Column(name = "cph_cluster_process_id", nullable = false)
	public long getCphClusterProcessId() {
		return this.cphClusterProcessId;
	}

	public void setCphClusterProcessId(long cphClusterProcessId) {
		this.cphClusterProcessId = cphClusterProcessId;
	}

	@Column(name = "cph_cluster_label_id", nullable = false)
	public long getCphClusterLabelId() {
		return this.cphClusterLabelId;
	}

	public void setCphClusterLabelId(long cphClusterLabelId) {
		this.cphClusterLabelId = cphClusterLabelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClusterProcessHasLabelsId))
			return false;
		ClusterProcessHasLabelsId castOther = (ClusterProcessHasLabelsId) other;

		return (this.getCphClusterProcessId() == castOther.getCphClusterProcessId()) && (this.getCphClusterLabelId() == castOther.getCphClusterLabelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCphClusterProcessId();
		result = 37 * result + (int) this.getCphClusterLabelId();
		return result;
	}

}
