package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClusterProcessHasLabels generated by hbm2java
 */
@Entity
@Table(name = "cluster_process_has_labels")
public class ClusterProcessHasLabels implements java.io.Serializable {

	private ClusterProcessHasLabelsId id;
	private ClusterLabels clusterLabels;
	private ClusterProcesses clusterProcesses;

	public ClusterProcessHasLabels() {
	}

	public ClusterProcessHasLabels(ClusterProcessHasLabelsId id, ClusterLabels clusterLabels, ClusterProcesses clusterProcesses) {
		this.id = id;
		this.clusterLabels = clusterLabels;
		this.clusterProcesses = clusterProcesses;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "cphClusterProcessId", column = @Column(name = "cph_cluster_process_id", nullable = false)),
			@AttributeOverride(name = "cphClusterLabelId", column = @Column(name = "cph_cluster_label_id", nullable = false)) })
	public ClusterProcessHasLabelsId getId() {
		return this.id;
	}

	public void setId(ClusterProcessHasLabelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cph_cluster_label_id", nullable = false, insertable = false, updatable = false)
	public ClusterLabels getClusterLabels() {
		return this.clusterLabels;
	}

	public void setClusterLabels(ClusterLabels clusterLabels) {
		this.clusterLabels = clusterLabels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cph_cluster_process_id", nullable = false, insertable = false, updatable = false)
	public ClusterProcesses getClusterProcesses() {
		return this.clusterProcesses;
	}

	public void setClusterProcesses(ClusterProcesses clusterProcesses) {
		this.clusterProcesses = clusterProcesses;
	}

}
