package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClusterProperties generated by hbm2java
 */
@Entity
@Table(name = "cluster_properties")
public class ClusterProperties implements java.io.Serializable {

	private ClusterPropertiesId id;
	private ClusterProcesses clusterProcesses;
	private String clprPropValue;

	public ClusterProperties() {
	}

	public ClusterProperties(ClusterPropertiesId id, ClusterProcesses clusterProcesses, String clprPropValue) {
		this.id = id;
		this.clusterProcesses = clusterProcesses;
		this.clprPropValue = clprPropValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "clprClusterProcessId", column = @Column(name = "clpr_cluster_process_id", nullable = false)),
			@AttributeOverride(name = "clprPropKey", column = @Column(name = "clpr_prop_key", nullable = false)) })
	public ClusterPropertiesId getId() {
		return this.id;
	}

	public void setId(ClusterPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clpr_cluster_process_id", nullable = false, insertable = false, updatable = false)
	public ClusterProcesses getClusterProcesses() {
		return this.clusterProcesses;
	}

	public void setClusterProcesses(ClusterProcesses clusterProcesses) {
		this.clusterProcesses = clusterProcesses;
	}

	@Column(name = "clpr_prop_value", nullable = false)
	public String getClprPropValue() {
		return this.clprPropValue;
	}

	public void setClprPropValue(String clprPropValue) {
		this.clprPropValue = clprPropValue;
	}

}
