package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorpusPropertiesId generated by hbm2java
 */
@Embeddable
public class CorpusPropertiesId implements java.io.Serializable {

	private long copCorpusId;
	private String copPropKey;

	public CorpusPropertiesId() {
	}

	public CorpusPropertiesId(long copCorpusId, String copPropKey) {
		this.copCorpusId = copCorpusId;
		this.copPropKey = copPropKey;
	}

	@Column(name = "cop_corpus_id", nullable = false)
	public long getCopCorpusId() {
		return this.copCorpusId;
	}

	public void setCopCorpusId(long copCorpusId) {
		this.copCorpusId = copCorpusId;
	}

	@Column(name = "cop_prop_key", nullable = false)
	public String getCopPropKey() {
		return this.copPropKey;
	}

	public void setCopPropKey(String copPropKey) {
		this.copPropKey = copPropKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorpusPropertiesId))
			return false;
		CorpusPropertiesId castOther = (CorpusPropertiesId) other;

		return (this.getCopCorpusId() == castOther.getCopCorpusId())
				&& ((this.getCopPropKey() == castOther.getCopPropKey()) || (this.getCopPropKey() != null && castOther.getCopPropKey() != null && this.getCopPropKey().equals(
						castOther.getCopPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCopCorpusId();
		result = 37 * result + (getCopPropKey() == null ? 0 : this.getCopPropKey().hashCode());
		return result;
	}

}
