package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;
// Generated 21/jun/2016 18:34:36 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorpusHasPublicationsHasProcessesId generated by hbm2java
 */
@Embeddable
public class CorpusHasPublicationsHasProcessesId implements java.io.Serializable {

	private long chphpCorpusId;
	private long chphpPublicationId;
	private long chphpProcessesId;

	public CorpusHasPublicationsHasProcessesId() {
	}

	public CorpusHasPublicationsHasProcessesId(long chphpCorpusId, long chphpPublicationId, long chphpProcessesId) {
		this.chphpCorpusId = chphpCorpusId;
		this.chphpPublicationId = chphpPublicationId;
		this.chphpProcessesId = chphpProcessesId;
	}

	@Column(name = "chphp_corpus_id", nullable = false)
	public long getChphpCorpusId() {
		return this.chphpCorpusId;
	}

	public void setChphpCorpusId(long chphpCorpusId) {
		this.chphpCorpusId = chphpCorpusId;
	}

	@Column(name = "chphp_publication_id", nullable = false)
	public long getChphpPublicationId() {
		return this.chphpPublicationId;
	}

	public void setChphpPublicationId(long chphpPublicationId) {
		this.chphpPublicationId = chphpPublicationId;
	}

	@Column(name = "chphp_processes_id", nullable = false)
	public long getChphpProcessesId() {
		return this.chphpProcessesId;
	}

	public void setChphpProcessesId(long chphpProcessesId) {
		this.chphpProcessesId = chphpProcessesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorpusHasPublicationsHasProcessesId))
			return false;
		CorpusHasPublicationsHasProcessesId castOther = (CorpusHasPublicationsHasProcessesId) other;

		return (this.getChphpCorpusId() == castOther.getChphpCorpusId())
				&& (this.getChphpPublicationId() == castOther.getChphpPublicationId())
				&& (this.getChphpProcessesId() == castOther.getChphpProcessesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getChphpCorpusId();
		result = 37 * result + (int) this.getChphpPublicationId();
		result = 37 * result + (int) this.getChphpProcessesId();
		return result;
	}

}
