package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CorpusProperties generated by hbm2java
 */
@Entity
@Table(name = "corpus_properties")
public class CorpusProperties implements java.io.Serializable {

	private CorpusPropertiesId id;
	private Corpus corpus;
	private String copPropValue;

	public CorpusProperties() {
	}

	public CorpusProperties(CorpusPropertiesId id, Corpus corpus, String copPropValue) {
		this.id = id;
		this.corpus = corpus;
		this.copPropValue = copPropValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "copCorpusId", column = @Column(name = "cop_corpus_id", nullable = false)),
			@AttributeOverride(name = "copPropKey", column = @Column(name = "cop_prop_key", nullable = false)) })
	public CorpusPropertiesId getId() {
		return this.id;
	}

	public void setId(CorpusPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cop_corpus_id", nullable = false, insertable = false, updatable = false)
	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	@Column(name = "cop_prop_value", nullable = false)
	public String getCopPropValue() {
		return this.copPropValue;
	}

	public void setCopPropValue(String copPropValue) {
		this.copPropValue = copPropValue;
	}

}
