package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CorpusHasProcesses generated by hbm2java
 */
@Entity
@Table(name = "corpus_has_processes")
public class CorpusHasProcesses implements java.io.Serializable {

	private CorpusHasProcessesId id;
	private Corpus corpus;
	private Processes processes;

	public CorpusHasProcesses() {
	}

	public CorpusHasProcesses(CorpusHasProcessesId id, Corpus corpus, Processes processes) {
		this.id = id;
		this.corpus = corpus;
		this.processes = processes;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "chpCorpusId", column = @Column(name = "chp_corpus_id", nullable = false)),
			@AttributeOverride(name = "chpProcessId", column = @Column(name = "chp_process_id", nullable = false)) })
	public CorpusHasProcessesId getId() {
		return this.id;
	}

	public void setId(CorpusHasProcessesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chp_corpus_id", nullable = false, insertable = false, updatable = false)
	public Corpus getCorpus() {
		return this.corpus;
	}

	public void setCorpus(Corpus corpus) {
		this.corpus = corpus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chp_process_id", nullable = false, insertable = false, updatable = false)
	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

}
