package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorpusHasProcessesId generated by hbm2java
 */
@Embeddable
public class CorpusHasProcessesId implements java.io.Serializable {

	private long chpCorpusId;
	private long chpProcessId;

	public CorpusHasProcessesId() {
	}

	public CorpusHasProcessesId(long chpCorpusId, long chpProcessId) {
		this.chpCorpusId = chpCorpusId;
		this.chpProcessId = chpProcessId;
	}

	@Column(name = "chp_corpus_id", nullable = false)
	public long getChpCorpusId() {
		return this.chpCorpusId;
	}

	public void setChpCorpusId(long chpCorpusId) {
		this.chpCorpusId = chpCorpusId;
	}

	@Column(name = "chp_process_id", nullable = false)
	public long getChpProcessId() {
		return this.chpProcessId;
	}

	public void setChpProcessId(long chpProcessId) {
		this.chpProcessId = chpProcessId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorpusHasProcessesId))
			return false;
		CorpusHasProcessesId castOther = (CorpusHasProcessesId) other;

		return (this.getChpCorpusId() == castOther.getChpCorpusId()) && (this.getChpProcessId() == castOther.getChpProcessId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getChpCorpusId();
		result = 37 * result + (int) this.getChpProcessId();
		return result;
	}

}
