package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;
// Generated 21/jun/2016 18:34:36 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataProcessStatus generated by hbm2java
 */
@Entity
@Table(name = "data_process_status")
public class DataProcessStatus implements java.io.Serializable {

	private int dpsId;
	private long dpsDataObjectId;
	private String dpsTypeResource;
	private String dpsStatus;
	private String dpsReport;
	private Float dpsProgress;
	private Date dpsCreateDate;
	private Date dpsUpdateDate;
	private Date dpsFinishDate;
	private AuthUsers authUsers;

	public DataProcessStatus() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "dps_id",unique = true, nullable = false)
	public int getDpsId() {
		return dpsId;
	}


	public void setDpsId(int dpsId) {
		this.dpsId = dpsId;
	}

	@Column(name = "dps_data_object_id", nullable = false)
	public long getDpsDataObjectId() {
		return dpsDataObjectId;
	}


	public void setDpsDataObjectId(long dpsDataObjectId) {
		this.dpsDataObjectId = dpsDataObjectId;
	}

	@Column(name = "dps_type_resource", nullable = false, length = 20)
	public String getDpsTypeResource() {
		return dpsTypeResource;
	}


	public void setDpsTypeResource(String dpsTypeResource) {
		this.dpsTypeResource = dpsTypeResource;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "dps_users_id")
	public AuthUsers getAuthUsers() {
		return this.authUsers;
	}

	public void setAuthUsers(AuthUsers authUsers) {
		this.authUsers = authUsers;
	}

	@Column(name = "dps_status", nullable = false, length = 8)
	public String getDpsStatus() {
		return this.dpsStatus;
	}

	public void setDpsStatus(String dpsStatus) {
		this.dpsStatus = dpsStatus;
	}

	@Column(name = "dps_report")
	public String getDpsReport() {
		return this.dpsReport;
	}

	public void setDpsReport(String dpsReport) {
		this.dpsReport = dpsReport;
	}

	@Column(name = "dps_progress", precision = 12, scale = 0)
	public Float getDpsProgress() {
		return this.dpsProgress;
	}

	public void setDpsProgress(Float dpsProgress) {
		this.dpsProgress = dpsProgress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dps_create_date", length = 19)
	public Date getDpsCreateDate() {
		return this.dpsCreateDate;
	}

	public void setDpsCreateDate(Date dpsCreateDate) {
		this.dpsCreateDate = dpsCreateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dps_update_date", length = 19)
	public Date getDpsUpdateDate() {
		return this.dpsUpdateDate;
	}

	public void setDpsUpdateDate(Date dpsUpdateDate) {
		this.dpsUpdateDate = dpsUpdateDate;
	}

	@Column(name = "dps_finish_date", length = 10,nullable = true)
	public Date getDpsFinishDate() {
		return this.dpsFinishDate;
	}

	public void setDpsFinishDate(Date dpsFinishDate) {
		this.dpsFinishDate = dpsFinishDate;
	}



}
