package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;
// Generated 21/jun/2016 18:34:36 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DataProcessStatusId generated by hbm2java
 */
@Embeddable
public class DataProcessStatusId implements java.io.Serializable {

	private long dpsDataObjectId;
	private String dpsTypeResource;

	public DataProcessStatusId() {
	}

	public DataProcessStatusId(long dpsDataObjectId, String dpsTypeResource) {
		this.dpsDataObjectId = dpsDataObjectId;
		this.dpsTypeResource = dpsTypeResource;
	}

	@Column(name = "dps_data_object_id", nullable = false)
	public long getDpsDataObjectId() {
		return this.dpsDataObjectId;
	}

	public void setDpsDataObjectId(long dpsDataObjectId) {
		this.dpsDataObjectId = dpsDataObjectId;
	}

	@Column(name = "dps_type_resource", nullable = false, length = 9)
	public String getDpsTypeResource() {
		return this.dpsTypeResource;
	}

	public void setDpsTypeResource(String dpsTypeResource) {
		this.dpsTypeResource = dpsTypeResource;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DataProcessStatusId))
			return false;
		DataProcessStatusId castOther = (DataProcessStatusId) other;

		return (this.getDpsDataObjectId() == castOther.getDpsDataObjectId())
				&& ((this.getDpsTypeResource() == castOther.getDpsTypeResource())
						|| (this.getDpsTypeResource() != null && castOther.getDpsTypeResource() != null
								&& this.getDpsTypeResource().equals(castOther.getDpsTypeResource())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDpsDataObjectId();
		result = 37 * result + (getDpsTypeResource() == null ? 0 : this.getDpsTypeResource().hashCode());
		return result;
	}

}
