package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HyperLinkSubmenusId generated by hbm2java
 */
@Embeddable
public class HyperLinkSubmenusId implements java.io.Serializable {

	private long hyliHyperLinkMenuId;
	private long hyliHyperLinkSubmenuId;

	public HyperLinkSubmenusId() {
	}

	public HyperLinkSubmenusId(long hyliHyperLinkMenuId, long hyliHyperLinkSubmenuId) {
		this.hyliHyperLinkMenuId = hyliHyperLinkMenuId;
		this.hyliHyperLinkSubmenuId = hyliHyperLinkSubmenuId;
	}

	@Column(name = "hyli_hyper_link_menu_id", nullable = false)
	public long getHyliHyperLinkMenuId() {
		return this.hyliHyperLinkMenuId;
	}

	public void setHyliHyperLinkMenuId(long hyliHyperLinkMenuId) {
		this.hyliHyperLinkMenuId = hyliHyperLinkMenuId;
	}

	@Column(name = "hyli_hyper_link_submenu_id", nullable = false)
	public long getHyliHyperLinkSubmenuId() {
		return this.hyliHyperLinkSubmenuId;
	}

	public void setHyliHyperLinkSubmenuId(long hyliHyperLinkSubmenuId) {
		this.hyliHyperLinkSubmenuId = hyliHyperLinkSubmenuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HyperLinkSubmenusId))
			return false;
		HyperLinkSubmenusId castOther = (HyperLinkSubmenusId) other;

		return (this.getHyliHyperLinkMenuId() == castOther.getHyliHyperLinkMenuId()) && (this.getHyliHyperLinkSubmenuId() == castOther.getHyliHyperLinkSubmenuId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getHyliHyperLinkMenuId();
		result = 37 * result + (int) this.getHyliHyperLinkSubmenuId();
		return result;
	}

}
