package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HyperLinkMenuSourceAssociationId generated by hbm2java
 */
@Embeddable
public class HyperLinkMenuSourceAssociationId implements java.io.Serializable {

	private long hlmHyperLinksMenuId;
	private long hlmSourceId;

	public HyperLinkMenuSourceAssociationId() {
	}

	public HyperLinkMenuSourceAssociationId(long hlmHyperLinksMenuId, long hlmSourceId) {
		this.hlmHyperLinksMenuId = hlmHyperLinksMenuId;
		this.hlmSourceId = hlmSourceId;
	}

	@Column(name = "hlm_hyper_links_menu_id", nullable = false)
	public long getHlmHyperLinksMenuId() {
		return this.hlmHyperLinksMenuId;
	}

	public void setHlmHyperLinksMenuId(long hlmHyperLinksMenuId) {
		this.hlmHyperLinksMenuId = hlmHyperLinksMenuId;
	}

	@Column(name = "hlm_source_id", nullable = false)
	public long getHlmSourceId() {
		return this.hlmSourceId;
	}

	public void setHlmSourceId(long hlmSourceId) {
		this.hlmSourceId = hlmSourceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HyperLinkMenuSourceAssociationId))
			return false;
		HyperLinkMenuSourceAssociationId castOther = (HyperLinkMenuSourceAssociationId) other;

		return (this.getHlmHyperLinksMenuId() == castOther.getHlmHyperLinksMenuId()) && (this.getHlmSourceId() == castOther.getHlmSourceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getHlmHyperLinksMenuId();
		result = 37 * result + (int) this.getHlmSourceId();
		return result;
	}

}
