package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HyperLinkMenuSourceAssociation generated by hbm2java
 */
@Entity
@Table(name = "hyper_link_menu_source_association")
public class HyperLinkMenuSourceAssociation implements java.io.Serializable {

	private HyperLinkMenuSourceAssociationId id;
	private HyperLinkMenus hyperLinkMenus;
	private Sources sources;

	public HyperLinkMenuSourceAssociation() {
	}

	public HyperLinkMenuSourceAssociation(HyperLinkMenuSourceAssociationId id, HyperLinkMenus hyperLinkMenus, Sources sources) {
		this.id = id;
		this.hyperLinkMenus = hyperLinkMenus;
		this.sources = sources;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "hlmHyperLinksMenuId", column = @Column(name = "hlm_hyper_links_menu_id", nullable = false)),
			@AttributeOverride(name = "hlmSourceId", column = @Column(name = "hlm_source_id", nullable = false)) })
	public HyperLinkMenuSourceAssociationId getId() {
		return this.id;
	}

	public void setId(HyperLinkMenuSourceAssociationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hlm_hyper_links_menu_id", nullable = false, insertable = false, updatable = false)
	public HyperLinkMenus getHyperLinkMenus() {
		return this.hyperLinkMenus;
	}

	public void setHyperLinkMenus(HyperLinkMenus hyperLinkMenus) {
		this.hyperLinkMenus = hyperLinkMenus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hlm_source_id", nullable = false, insertable = false, updatable = false)
	public Sources getSources() {
		return this.sources;
	}

	public void setSources(Sources sources) {
		this.sources = sources;
	}

}
