package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HyperLinkMenus generated by hbm2java
 */
@Entity
@Table(name = "hyper_link_menus")
public class HyperLinkMenus implements java.io.Serializable {

	private long hylId;
	private String hylMenuName;
	private String hylHyperLinkMenu;
	private byte[] hylIcon;
	private String hylMenuLevel;
	private Set<HyperLinkMenuSourceAssociation> hyperLinkMenuSourceAssociations = new HashSet<HyperLinkMenuSourceAssociation>(0);
	private Set<HyperLinkSubmenus> hyperLinkSubmenusesForHyliHyperLinkMenuId = new HashSet<HyperLinkSubmenus>(0);
	private Set<HyperLinkSubmenus> hyperLinkSubmenusesForHyliHyperLinkSubmenuId = new HashSet<HyperLinkSubmenus>(0);

	public HyperLinkMenus() {
	}

	public HyperLinkMenus(long hylId, String hylMenuName, String hylHyperLinkMenu, String hylMenuLevel) {
		this.hylId = hylId;
		this.hylMenuName = hylMenuName;
		this.hylHyperLinkMenu = hylHyperLinkMenu;
		this.hylMenuLevel = hylMenuLevel;
	}

	public HyperLinkMenus(long hylId, String hylMenuName, String hylHyperLinkMenu, byte[] hylIcon, String hylMenuLevel,
			Set<HyperLinkMenuSourceAssociation> hyperLinkMenuSourceAssociations, Set<HyperLinkSubmenus> hyperLinkSubmenusesForHyliHyperLinkMenuId,
			Set<HyperLinkSubmenus> hyperLinkSubmenusesForHyliHyperLinkSubmenuId) {
		this.hylId = hylId;
		this.hylMenuName = hylMenuName;
		this.hylHyperLinkMenu = hylHyperLinkMenu;
		this.hylIcon = hylIcon;
		this.hylMenuLevel = hylMenuLevel;
		this.hyperLinkMenuSourceAssociations = hyperLinkMenuSourceAssociations;
		this.hyperLinkSubmenusesForHyliHyperLinkMenuId = hyperLinkSubmenusesForHyliHyperLinkMenuId;
		this.hyperLinkSubmenusesForHyliHyperLinkSubmenuId = hyperLinkSubmenusesForHyliHyperLinkSubmenuId;
	}

	@Id
	@Column(name = "hyl_id", unique = true, nullable = false)
	public long getHylId() {
		return this.hylId;
	}

	public void setHylId(long hylId) {
		this.hylId = hylId;
	}

	@Column(name = "hyl_menu_name", nullable = false, length = 45)
	public String getHylMenuName() {
		return this.hylMenuName;
	}

	public void setHylMenuName(String hylMenuName) {
		this.hylMenuName = hylMenuName;
	}

	@Column(name = "hyl_hyper_link_menu", nullable = false, length = 250)
	public String getHylHyperLinkMenu() {
		return this.hylHyperLinkMenu;
	}

	public void setHylHyperLinkMenu(String hylHyperLinkMenu) {
		this.hylHyperLinkMenu = hylHyperLinkMenu;
	}

	@Column(name = "hyl_icon")
	public byte[] getHylIcon() {
		return this.hylIcon;
	}

	public void setHylIcon(byte[] hylIcon) {
		this.hylIcon = hylIcon;
	}

	@Column(name = "hyl_menu_level", nullable = false, length = 2)
	public String getHylMenuLevel() {
		return this.hylMenuLevel;
	}

	public void setHylMenuLevel(String hylMenuLevel) {
		this.hylMenuLevel = hylMenuLevel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyperLinkMenus")
	public Set<HyperLinkMenuSourceAssociation> getHyperLinkMenuSourceAssociations() {
		return this.hyperLinkMenuSourceAssociations;
	}

	public void setHyperLinkMenuSourceAssociations(Set<HyperLinkMenuSourceAssociation> hyperLinkMenuSourceAssociations) {
		this.hyperLinkMenuSourceAssociations = hyperLinkMenuSourceAssociations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyperLinkMenusByHyliHyperLinkMenuId")
	public Set<HyperLinkSubmenus> getHyperLinkSubmenusesForHyliHyperLinkMenuId() {
		return this.hyperLinkSubmenusesForHyliHyperLinkMenuId;
	}

	public void setHyperLinkSubmenusesForHyliHyperLinkMenuId(Set<HyperLinkSubmenus> hyperLinkSubmenusesForHyliHyperLinkMenuId) {
		this.hyperLinkSubmenusesForHyliHyperLinkMenuId = hyperLinkSubmenusesForHyliHyperLinkMenuId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hyperLinkMenusByHyliHyperLinkSubmenuId")
	public Set<HyperLinkSubmenus> getHyperLinkSubmenusesForHyliHyperLinkSubmenuId() {
		return this.hyperLinkSubmenusesForHyliHyperLinkSubmenuId;
	}

	public void setHyperLinkSubmenusesForHyliHyperLinkSubmenuId(Set<HyperLinkSubmenus> hyperLinkSubmenusesForHyliHyperLinkSubmenuId) {
		this.hyperLinkSubmenusesForHyliHyperLinkSubmenuId = hyperLinkSubmenusesForHyliHyperLinkSubmenuId;
	}

}
