package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessEntitiesStatsId generated by hbm2java
 */
@Embeddable
public class ProcessEntitiesStatsId implements java.io.Serializable {

	private long annProcessId;
	private String annElement;
	private long numberElements;
	private String claName;

	public ProcessEntitiesStatsId() {
	}

	public ProcessEntitiesStatsId(long annProcessId, long numberElements, String claName) {
		this.annProcessId = annProcessId;
		this.numberElements = numberElements;
		this.claName = claName;
	}

	public ProcessEntitiesStatsId(long annProcessId, String annElement, long numberElements, String claName) {
		this.annProcessId = annProcessId;
		this.annElement = annElement;
		this.numberElements = numberElements;
		this.claName = claName;
	}

	@Column(name = "ann_process_id", nullable = false)
	public long getAnnProcessId() {
		return this.annProcessId;
	}

	public void setAnnProcessId(long annProcessId) {
		this.annProcessId = annProcessId;
	}

	@Column(name = "ann_element", length = 500)
	public String getAnnElement() {
		return this.annElement;
	}

	public void setAnnElement(String annElement) {
		this.annElement = annElement;
	}

	@Column(name = "numberElements", nullable = false)
	public long getNumberElements() {
		return this.numberElements;
	}

	public void setNumberElements(long numberElements) {
		this.numberElements = numberElements;
	}

	@Column(name = "cla_name", nullable = false)
	public String getClaName() {
		return this.claName;
	}

	public void setClaName(String claName) {
		this.claName = claName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessEntitiesStatsId))
			return false;
		ProcessEntitiesStatsId castOther = (ProcessEntitiesStatsId) other;

		return (this.getAnnProcessId() == castOther.getAnnProcessId())
				&& ((this.getAnnElement() == castOther.getAnnElement()) || (this.getAnnElement() != null && castOther.getAnnElement() != null && this.getAnnElement().equals(
						castOther.getAnnElement())))
				&& (this.getNumberElements() == castOther.getNumberElements())
				&& ((this.getClaName() == castOther.getClaName()) || (this.getClaName() != null && castOther.getClaName() != null && this.getClaName().equals(
						castOther.getClaName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAnnProcessId();
		result = 37 * result + (getAnnElement() == null ? 0 : this.getAnnElement().hashCode());
		result = 37 * result + (int) this.getNumberElements();
		result = 37 * result + (getClaName() == null ? 0 : this.getClaName().hashCode());
		return result;
	}

}
