package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessPropertiesId generated by hbm2java
 */
@Embeddable
public class ProcessPropertiesId implements java.io.Serializable {

	private long pprProcessId;
	private String pprPropKey;

	public ProcessPropertiesId() {
	}

	public ProcessPropertiesId(long pprProcessId, String pprPropKey) {
		this.pprProcessId = pprProcessId;
		this.pprPropKey = pprPropKey;
	}

	@Column(name = "ppr_process_id", nullable = false)
	public long getPprProcessId() {
		return this.pprProcessId;
	}

	public void setPprProcessId(long pprProcessId) {
		this.pprProcessId = pprProcessId;
	}

	@Column(name = "ppr_prop_key", nullable = false)
	public String getPprPropKey() {
		return this.pprPropKey;
	}

	public void setPprPropKey(String pprPropKey) {
		this.pprPropKey = pprPropKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessPropertiesId))
			return false;
		ProcessPropertiesId castOther = (ProcessPropertiesId) other;

		return (this.getPprProcessId() == castOther.getPprProcessId())
				&& ((this.getPprPropKey() == castOther.getPprPropKey()) || (this.getPprPropKey() != null && castOther.getPprPropKey() != null && this.getPprPropKey().equals(
						castOther.getPprPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPprProcessId();
		result = 37 * result + (getPprPropKey() == null ? 0 : this.getPprPropKey().hashCode());
		return result;
	}

}
