package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProcessTypes generated by hbm2java
 */
@Entity
@Table(name = "process_types", uniqueConstraints = @UniqueConstraint(columnNames = "pt_process_type"))
public class ProcessTypes implements java.io.Serializable {

	private long ptId;
	private String ptProcessType;
	private Set<Processes> processeses = new HashSet<Processes>(0);

	public ProcessTypes() {
	}

	public ProcessTypes(long ptId, String ptProcessType) {
		this.ptId = ptId;
		this.ptProcessType = ptProcessType;
	}

	public ProcessTypes(long ptId, String ptProcessType, Set<Processes> processeses) {
		this.ptId = ptId;
		this.ptProcessType = ptProcessType;
		this.processeses = processeses;
	}

	@Id
	@Column(name = "pt_id", unique = true, nullable = false)
	public long getPtId() {
		return this.ptId;
	}

	public void setPtId(long ptId) {
		this.ptId = ptId;
	}

	@Column(name = "pt_process_type", unique = true, nullable = false)
	public String getPtProcessType() {
		return this.ptProcessType;
	}

	public void setPtProcessType(String ptProcessType) {
		this.ptProcessType = ptProcessType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processTypes")
	public Set<Processes> getProcesseses() {
		return this.processeses;
	}

	public void setProcesseses(Set<Processes> processeses) {
		this.processeses = processeses;
	}

}
