package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessProperties generated by hbm2java
 */
@Entity
@Table(name = "process_properties")
public class ProcessProperties implements java.io.Serializable {

	private ProcessPropertiesId id;
	private Processes processes;
	private String pprPropValue;

	public ProcessProperties() {
	}

	public ProcessProperties(ProcessPropertiesId id, Processes processes, String pprPropValue) {
		this.id = id;
		this.processes = processes;
		this.pprPropValue = pprPropValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "pprProcessId", column = @Column(name = "ppr_process_id", nullable = false)),
			@AttributeOverride(name = "pprPropKey", column = @Column(name = "ppr_prop_key", nullable = false)) })
	public ProcessPropertiesId getId() {
		return this.id;
	}

	public void setId(ProcessPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ppr_process_id", nullable = false, insertable = false, updatable = false)
	public Processes getProcesses() {
		return this.processes;
	}

	public void setProcesses(Processes processes) {
		this.processes = processes;
	}

	@Column(name = "ppr_prop_value", nullable = false)
	public String getPprPropValue() {
		return this.pprPropValue;
	}

	public void setPprPropValue(String pprPropValue) {
		this.pprPropValue = pprPropValue;
	}

}
