package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcessGeneralResumeStats generated by hbm2java
 */
@Entity
@Table(name = "process_general_resume_stats")
public class ProcessGeneralResumeStats implements java.io.Serializable {

	private ProcessGeneralResumeStatsId id;

	public ProcessGeneralResumeStats() {
	}

	public ProcessGeneralResumeStats(ProcessGeneralResumeStatsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "annProcessId", column = @Column(name = "ann_process_id", nullable = false)),
			@AttributeOverride(name = "annAnnotType", column = @Column(name = "ann_annot_type", nullable = false, length = 4)),
			@AttributeOverride(name = "numberType", column = @Column(name = "numberType", nullable = false)) })
	public ProcessGeneralResumeStatsId getId() {
		return this.id;
	}

	public void setId(ProcessGeneralResumeStatsId id) {
		this.id = id;
	}

}
