package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcessEntitiesClassStats generated by hbm2java
 */
@Entity
@Table(name = "process_entities_class_stats")
public class ProcessEntitiesClassStats implements java.io.Serializable {

	private ProcessEntitiesClassStatsId id;

	public ProcessEntitiesClassStats() {
	}

	public ProcessEntitiesClassStats(ProcessEntitiesClassStatsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "annProcessId", column = @Column(name = "ann_process_id", nullable = false)),
			@AttributeOverride(name = "claName", column = @Column(name = "cla_name", nullable = false)),
			@AttributeOverride(name = "numberClasses", column = @Column(name = "numberClasses", nullable = false)) })
	public ProcessEntitiesClassStatsId getId() {
		return this.id;
	}

	public void setId(ProcessEntitiesClassStatsId id) {
		this.id = id;
	}

}
