package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessGeneralResumeStatsId generated by hbm2java
 */
@Embeddable
public class ProcessGeneralResumeStatsId implements java.io.Serializable {

	private long annProcessId;
	private String annAnnotType;
	private long numberType;

	public ProcessGeneralResumeStatsId() {
	}

	public ProcessGeneralResumeStatsId(long annProcessId, String annAnnotType, long numberType) {
		this.annProcessId = annProcessId;
		this.annAnnotType = annAnnotType;
		this.numberType = numberType;
	}

	@Column(name = "ann_process_id", nullable = false)
	public long getAnnProcessId() {
		return this.annProcessId;
	}

	public void setAnnProcessId(long annProcessId) {
		this.annProcessId = annProcessId;
	}

	@Column(name = "ann_annot_type", nullable = false, length = 4)
	public String getAnnAnnotType() {
		return this.annAnnotType;
	}

	public void setAnnAnnotType(String annAnnotType) {
		this.annAnnotType = annAnnotType;
	}

	@Column(name = "numberType", nullable = false)
	public long getNumberType() {
		return this.numberType;
	}

	public void setNumberType(long numberType) {
		this.numberType = numberType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessGeneralResumeStatsId))
			return false;
		ProcessGeneralResumeStatsId castOther = (ProcessGeneralResumeStatsId) other;

		return (this.getAnnProcessId() == castOther.getAnnProcessId())
				&& ((this.getAnnAnnotType() == castOther.getAnnAnnotType()) || (this.getAnnAnnotType() != null && castOther.getAnnAnnotType() != null && this.getAnnAnnotType()
						.equals(castOther.getAnnAnnotType()))) && (this.getNumberType() == castOther.getNumberType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAnnProcessId();
		result = 37 * result + (getAnnAnnotType() == null ? 0 : this.getAnnAnnotType().hashCode());
		result = 37 * result + (int) this.getNumberType();
		return result;
	}

}
