package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessEntitiesClassStatsId generated by hbm2java
 */
@Embeddable
public class ProcessEntitiesClassStatsId implements java.io.Serializable {

	private long annProcessId;
	private String claName;
	private long numberClasses;

	public ProcessEntitiesClassStatsId() {
	}

	public ProcessEntitiesClassStatsId(long annProcessId, String claName, long numberClasses) {
		this.annProcessId = annProcessId;
		this.claName = claName;
		this.numberClasses = numberClasses;
	}

	@Column(name = "ann_process_id", nullable = false)
	public long getAnnProcessId() {
		return this.annProcessId;
	}

	public void setAnnProcessId(long annProcessId) {
		this.annProcessId = annProcessId;
	}

	@Column(name = "cla_name", nullable = false)
	public String getClaName() {
		return this.claName;
	}

	public void setClaName(String claName) {
		this.claName = claName;
	}

	@Column(name = "numberClasses", nullable = false)
	public long getNumberClasses() {
		return this.numberClasses;
	}

	public void setNumberClasses(long numberClasses) {
		this.numberClasses = numberClasses;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessEntitiesClassStatsId))
			return false;
		ProcessEntitiesClassStatsId castOther = (ProcessEntitiesClassStatsId) other;

		return (this.getAnnProcessId() == castOther.getAnnProcessId())
				&& ((this.getClaName() == castOther.getClaName()) || (this.getClaName() != null && castOther.getClaName() != null && this.getClaName().equals(
						castOther.getClaName()))) && (this.getNumberClasses() == castOther.getNumberClasses());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAnnProcessId();
		result = 37 * result + (getClaName() == null ? 0 : this.getClaName().hashCode());
		result = 37 * result + (int) this.getNumberClasses();
		return result;
	}

}
