package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessCluesStatsId generated by hbm2java
 */
@Embeddable
public class ProcessCluesStatsId implements java.io.Serializable {

	private long annProcessId;
	private String annClue;
	private long numberClues;
	private String annClassificationRe;

	public ProcessCluesStatsId() {
	}

	public ProcessCluesStatsId(long annProcessId, long numberClues) {
		this.annProcessId = annProcessId;
		this.numberClues = numberClues;
	}

	public ProcessCluesStatsId(long annProcessId, String annClue, long numberClues, String annClassificationRe) {
		this.annProcessId = annProcessId;
		this.annClue = annClue;
		this.numberClues = numberClues;
		this.annClassificationRe = annClassificationRe;
	}

	@Column(name = "ann_process_id", nullable = false)
	public long getAnnProcessId() {
		return this.annProcessId;
	}

	public void setAnnProcessId(long annProcessId) {
		this.annProcessId = annProcessId;
	}

	@Column(name = "ann_clue", length = 250)
	public String getAnnClue() {
		return this.annClue;
	}

	public void setAnnClue(String annClue) {
		this.annClue = annClue;
	}

	@Column(name = "numberClues", nullable = false)
	public long getNumberClues() {
		return this.numberClues;
	}

	public void setNumberClues(long numberClues) {
		this.numberClues = numberClues;
	}

	@Column(name = "ann_classification_re", length = 250)
	public String getAnnClassificationRe() {
		return this.annClassificationRe;
	}

	public void setAnnClassificationRe(String annClassificationRe) {
		this.annClassificationRe = annClassificationRe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessCluesStatsId))
			return false;
		ProcessCluesStatsId castOther = (ProcessCluesStatsId) other;

		return (this.getAnnProcessId() == castOther.getAnnProcessId())
				&& ((this.getAnnClue() == castOther.getAnnClue()) || (this.getAnnClue() != null && castOther.getAnnClue() != null && this.getAnnClue().equals(
						castOther.getAnnClue())))
				&& (this.getNumberClues() == castOther.getNumberClues())
				&& ((this.getAnnClassificationRe() == castOther.getAnnClassificationRe()) || (this.getAnnClassificationRe() != null && castOther.getAnnClassificationRe() != null && this
						.getAnnClassificationRe().equals(castOther.getAnnClassificationRe())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAnnProcessId();
		result = 37 * result + (getAnnClue() == null ? 0 : this.getAnnClue().hashCode());
		result = 37 * result + (int) this.getNumberClues();
		result = 37 * result + (getAnnClassificationRe() == null ? 0 : this.getAnnClassificationRe().hashCode());
		return result;
	}

}
