package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcessEntitiesStats generated by hbm2java
 */
@Entity
@Table(name = "process_entities_stats")
public class ProcessEntitiesStats implements java.io.Serializable {

	private ProcessEntitiesStatsId id;

	public ProcessEntitiesStats() {
	}

	public ProcessEntitiesStats(ProcessEntitiesStatsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "annProcessId", column = @Column(name = "ann_process_id", nullable = false)),
			@AttributeOverride(name = "annElement", column = @Column(name = "ann_element", length = 500)),
			@AttributeOverride(name = "numberElements", column = @Column(name = "numberElements", nullable = false)),
			@AttributeOverride(name = "claName", column = @Column(name = "cla_name", nullable = false)) })
	public ProcessEntitiesStatsId getId() {
		return this.id;
	}

	public void setId(ProcessEntitiesStatsId id) {
		this.id = id;
	}

}
