package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicationHasLabelsId generated by hbm2java
 */
@Embeddable
public class PublicationHasLabelsId implements java.io.Serializable {

	private long phpPublicationId;
	private long phpPublicationLabelId;

	public PublicationHasLabelsId() {
	}

	public PublicationHasLabelsId(long phpPublicationId, long phpPublicationLabelId) {
		this.phpPublicationId = phpPublicationId;
		this.phpPublicationLabelId = phpPublicationLabelId;
	}

	@Column(name = "php_publication_id", nullable = false)
	public long getPhpPublicationId() {
		return this.phpPublicationId;
	}

	public void setPhpPublicationId(long phpPublicationId) {
		this.phpPublicationId = phpPublicationId;
	}

	@Column(name = "php_publication_label_id", nullable = false)
	public long getPhpPublicationLabelId() {
		return this.phpPublicationLabelId;
	}

	public void setPhpPublicationLabelId(long phpPublicationLabelId) {
		this.phpPublicationLabelId = phpPublicationLabelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicationHasLabelsId))
			return false;
		PublicationHasLabelsId castOther = (PublicationHasLabelsId) other;

		return (this.getPhpPublicationId() == castOther.getPhpPublicationId()) && (this.getPhpPublicationLabelId() == castOther.getPhpPublicationLabelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPhpPublicationId();
		result = 37 * result + (int) this.getPhpPublicationLabelId();
		return result;
	}

}
