package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 25/Mai/2015 15:52:28 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PublicationFields generated by hbm2java
 */
@Entity
@Table(name = "publication_fields")
public class PublicationFields implements java.io.Serializable {

	private PublicationFieldsId id;
	private Publications publications;
	private long pflFieldStart;
	private long pflFieldEnd;
	private String pflText;

	public PublicationFields() {
	}

	public PublicationFields(PublicationFieldsId id, Publications publications, long pflFieldStart, long pflFieldEnd, String pflText) {
		this.id = id;
		this.publications = publications;
		this.pflFieldStart = pflFieldStart;
		this.pflFieldEnd = pflFieldEnd;
		this.pflText = pflText;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "pflField", column = @Column(name = "pfl_field", nullable = false)),
			@AttributeOverride(name = "pflPublicationId", column = @Column(name = "pfl_publication_id", nullable = false)) })
	public PublicationFieldsId getId() {
		return this.id;
	}

	public void setId(PublicationFieldsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfl_publication_id", nullable = false, insertable = false, updatable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	@Column(name = "pfl_field_start", nullable = false)
	public long getPflFieldStart() {
		return this.pflFieldStart;
	}

	public void setPflFieldStart(long pflFieldStart) {
		this.pflFieldStart = pflFieldStart;
	}

	@Column(name = "pfl_field_end", nullable = false)
	public long getPflFieldEnd() {
		return this.pflFieldEnd;
	}

	public void setPflFieldEnd(long pflFieldEnd) {
		this.pflFieldEnd = pflFieldEnd;
	}

	@Column(name = "pfl_text", nullable = false, length = 9)
	public String getPflText() {
		return this.pflText;
	}

	public void setPflText(String pflText) {
		this.pflText = pflText;
	}

}
