package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PublicationSources generated by hbm2java
 */
@Entity
@Table(name = "publication_sources", uniqueConstraints = @UniqueConstraint(columnNames = "pss_description"))
public class PublicationSources implements java.io.Serializable {

	private long pssId;
	private String pssDescription;
	private Set<PublicationHasSources> publicationHasSourceses = new HashSet<PublicationHasSources>(0);

	public PublicationSources() {
	}

	public PublicationSources(long pssId, String pssDescription) {
		this.pssId = pssId;
		this.pssDescription = pssDescription;
	}

	public PublicationSources(long pssId, String pssDescription, Set<PublicationHasSources> publicationHasSourceses) {
		this.pssId = pssId;
		this.pssDescription = pssDescription;
		this.publicationHasSourceses = publicationHasSourceses;
	}

	@Id
	@Column(name = "pss_id", unique = true, nullable = false)
	public long getPssId() {
		return this.pssId;
	}

	public void setPssId(long pssId) {
		this.pssId = pssId;
	}

	@Column(name = "pss_description", unique = true, nullable = false)
	public String getPssDescription() {
		return this.pssDescription;
	}

	public void setPssDescription(String pssDescription) {
		this.pssDescription = pssDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publicationSources")
	public Set<PublicationHasSources> getPublicationHasSourceses() {
		return this.publicationHasSourceses;
	}

	public void setPublicationHasSourceses(Set<PublicationHasSources> publicationHasSourceses) {
		this.publicationHasSourceses = publicationHasSourceses;
	}

}
