package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicationFieldsId generated by hbm2java
 */
@Embeddable
public class PublicationFieldsId implements java.io.Serializable {

	private String pflField;
	private long pflPublicationId;

	public PublicationFieldsId() {
	}

	public PublicationFieldsId(String pflField, long pflPublicationId) {
		this.pflField = pflField;
		this.pflPublicationId = pflPublicationId;
	}

	@Column(name = "pfl_field", nullable = false)
	public String getPflField() {
		return this.pflField;
	}

	public void setPflField(String pflField) {
		this.pflField = pflField;
	}

	@Column(name = "pfl_publication_id", nullable = false)
	public long getPflPublicationId() {
		return this.pflPublicationId;
	}

	public void setPflPublicationId(long pflPublicationId) {
		this.pflPublicationId = pflPublicationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicationFieldsId))
			return false;
		PublicationFieldsId castOther = (PublicationFieldsId) other;

		return ((this.getPflField() == castOther.getPflField()) || (this.getPflField() != null && castOther.getPflField() != null && this.getPflField().equals(
				castOther.getPflField())))
				&& (this.getPflPublicationId() == castOther.getPflPublicationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPflField() == null ? 0 : this.getPflField().hashCode());
		result = 37 * result + (int) this.getPflPublicationId();
		return result;
	}

}
