package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 12/Mai/2015 15:02:03 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PublicationHasSourcesId generated by hbm2java
 */
@Embeddable
public class PublicationHasSourcesId implements java.io.Serializable {

	private long phpsPublicationSourceId;
	private String phpsPublicationSourceInternalId;
	private long phpsPublicationId;

	public PublicationHasSourcesId() {
	}

	public PublicationHasSourcesId(long phpsPublicationSourceId, String phpsPublicationSourceInternalId, long phpsPublicationId) {
		this.phpsPublicationSourceId = phpsPublicationSourceId;
		this.phpsPublicationSourceInternalId = phpsPublicationSourceInternalId;
		this.phpsPublicationId = phpsPublicationId;
	}

	@Column(name = "phps_publication_source_id", nullable = false)
	public long getPhpsPublicationSourceId() {
		return this.phpsPublicationSourceId;
	}

	public void setPhpsPublicationSourceId(long phpsPublicationSourceId) {
		this.phpsPublicationSourceId = phpsPublicationSourceId;
	}

	@Column(name = "phps_publication_source_internal_id", nullable = false)
	public String getPhpsPublicationSourceInternalId() {
		return this.phpsPublicationSourceInternalId;
	}

	public void setPhpsPublicationSourceInternalId(String phpsPublicationSourceInternalId) {
		this.phpsPublicationSourceInternalId = phpsPublicationSourceInternalId;
	}

	@Column(name = "phps_publication_id", nullable = false)
	public long getPhpsPublicationId() {
		return this.phpsPublicationId;
	}

	public void setPhpsPublicationId(long phpsPublicationId) {
		this.phpsPublicationId = phpsPublicationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicationHasSourcesId))
			return false;
		PublicationHasSourcesId castOther = (PublicationHasSourcesId) other;

		return (this.getPhpsPublicationSourceId() == castOther.getPhpsPublicationSourceId())
				&& ((this.getPhpsPublicationSourceInternalId() == castOther.getPhpsPublicationSourceInternalId()) || (this.getPhpsPublicationSourceInternalId() != null
						&& castOther.getPhpsPublicationSourceInternalId() != null && this.getPhpsPublicationSourceInternalId().equals(
						castOther.getPhpsPublicationSourceInternalId()))) && (this.getPhpsPublicationId() == castOther.getPhpsPublicationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPhpsPublicationSourceId();
		result = 37 * result + (getPhpsPublicationSourceInternalId() == null ? 0 : this.getPhpsPublicationSourceInternalId().hashCode());
		result = 37 * result + (int) this.getPhpsPublicationId();
		return result;
	}

}
