package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PublicationLabels generated by hbm2java
 */
@Entity
@Table(name = "publication_labels") //uniqueConstraints = @UniqueConstraint(columnNames = "pla_description")
public class PublicationLabels implements java.io.Serializable {

	private long plaId;
	private String plaDescription;
	private Set<PublicationHasLabels> publicationHasLabelses = new HashSet<PublicationHasLabels>(0);

	public PublicationLabels() {
	}

	public PublicationLabels(long plaId, String plaDescription) {
		this.plaId = plaId;
		this.plaDescription = plaDescription;
	}

	public PublicationLabels(long plaId, String plaDescription, Set<PublicationHasLabels> publicationHasLabelses) {
		this.plaId = plaId;
		this.plaDescription = plaDescription;
		this.publicationHasLabelses = publicationHasLabelses;
	}

	@Id
	@Column(name = "pla_id", unique = true, nullable = false)
	public long getPlaId() {
		return this.plaId;
	}

	public void setPlaId(long plaId) {
		this.plaId = plaId;
	}

	@Column(name = "pla_description", nullable = false) //unique = true
	public String getPlaDescription() {
		return this.plaDescription;
	}

	public void setPlaDescription(String plaDescription) {
		this.plaDescription = plaDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publicationLabels")
	public Set<PublicationHasLabels> getPublicationHasLabelses() {
		return this.publicationHasLabelses;
	}

	public void setPublicationHasLabelses(Set<PublicationHasLabels> publicationHasLabelses) {
		this.publicationHasLabelses = publicationHasLabelses;
	}

}
