package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PublicationHasLabels generated by hbm2java
 */
@Entity
@Table(name = "publication_has_labels")
public class PublicationHasLabels implements java.io.Serializable {

	private PublicationHasLabelsId id;
	private PublicationLabels publicationLabels;
	private Publications publications;

	public PublicationHasLabels() {
	}

	public PublicationHasLabels(PublicationHasLabelsId id, PublicationLabels publicationLabels, Publications publications) {
		this.id = id;
		this.publicationLabels = publicationLabels;
		this.publications = publications;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "phpPublicationId", column = @Column(name = "php_publication_id", nullable = false)),
			@AttributeOverride(name = "phpPublicationLabelId", column = @Column(name = "php_publication_label_id", nullable = false)) })
	public PublicationHasLabelsId getId() {
		return this.id;
	}

	public void setId(PublicationHasLabelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "php_publication_label_id", nullable = false, insertable = false, updatable = false)
	public PublicationLabels getPublicationLabels() {
		return this.publicationLabels;
	}

	public void setPublicationLabels(PublicationLabels publicationLabels) {
		this.publicationLabels = publicationLabels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "php_publication_id", nullable = false, insertable = false, updatable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

}
