package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QueryProperties generated by hbm2java
 */
@Entity
@Table(name = "query_properties")
public class QueryProperties implements java.io.Serializable {

	private QueryPropertiesId id;
	private Queries queries;
	private String qprPropValue;

	public QueryProperties() {
	}

	public QueryProperties(QueryPropertiesId id, Queries queries, String qprPropValue) {
		this.id = id;
		this.queries = queries;
		this.qprPropValue = qprPropValue;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "qprQueryId", column = @Column(name = "qpr_query_id", nullable = false)),
			@AttributeOverride(name = "qprPropKey", column = @Column(name = "qpr_prop_key", nullable = false)) })
	public QueryPropertiesId getId() {
		return this.id;
	}

	public void setId(QueryPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qpr_query_id", nullable = false, insertable = false, updatable = false)
	public Queries getQueries() {
		return this.queries;
	}

	public void setQueries(Queries queries) {
		this.queries = queries;
	}

	@Column(name = "qpr_prop_value", nullable = false)
	public String getQprPropValue() {
		return this.qprPropValue;
	}

	public void setQprPropValue(String qprPropValue) {
		this.qprPropValue = qprPropValue;
	}

}
