package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * QueryTypes generated by hbm2java
 */
@Entity
@Table(name = "query_types", uniqueConstraints = @UniqueConstraint(columnNames = "qt_description"))
public class QueryTypes implements java.io.Serializable {

	private long qtId;
	private String qtDescription;
	private Set<Queries> querieses = new HashSet<Queries>(0);

	public QueryTypes() {
	}

	public QueryTypes(long qtId) {
		this.qtId = qtId;
	}

	public QueryTypes(long qtId, String qtDescription, Set<Queries> querieses) {
		this.qtId = qtId;
		this.qtDescription = qtDescription;
		this.querieses = querieses;
	}

	@Id
	@Column(name = "qt_id", unique = true, nullable = false)
	public long getQtId() {
		return this.qtId;
	}

	public void setQtId(long qtId) {
		this.qtId = qtId;
	}

	@Column(name = "qt_description", unique = true)
	public String getQtDescription() {
		return this.qtDescription;
	}

	public void setQtDescription(String qtDescription) {
		this.qtDescription = qtDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "queryTypes")
	public Set<Queries> getQuerieses() {
		return this.querieses;
	}

	public void setQuerieses(Set<Queries> querieses) {
		this.querieses = querieses;
	}

}
