package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.annotations.IndexedEmbedded;

import com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.bridges.QueriesBridge;
import com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.bridges.QueryHasPublicationsBridge;
import com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.bridges.ResourceElementExtenalIdsIdBridge;

/**
 * QueryHasPublications generated by hbm2java
 */
@Entity
@Table(name = "query_has_publications")
public class QueryHasPublications implements java.io.Serializable {

	private QueryHasPublicationsId id;
	private Publications publications;
	private Queries queries;
	private String qhbRelevance;
	private Set<ClusterLabelPublications> clusterLabelPublicationses = new HashSet<ClusterLabelPublications>(0);

	public QueryHasPublications() {
	}

	public QueryHasPublications(QueryHasPublicationsId id, Publications publications, Queries queries) {
		this.id = id;
		this.publications = publications;
		this.queries = queries;
	}

	public QueryHasPublications(QueryHasPublicationsId id, Publications publications, Queries queries, String qhbRelevance, Set<ClusterLabelPublications> clusterLabelPublicationses) {
		this.id = id;
		this.publications = publications;
		this.queries = queries;
		this.qhbRelevance = qhbRelevance;
		this.clusterLabelPublicationses = clusterLabelPublicationses;
	}

	@EmbeddedId
	@DocumentId
	@FieldBridge(impl = QueryHasPublicationsBridge.class)
	@IndexedEmbedded
	@AttributeOverrides({ @AttributeOverride(name = "qhbQueryId", column = @Column(name = "qhb_query_id", nullable = false)),
			@AttributeOverride(name = "qhbPublicationId", column = @Column(name = "qhb_publication_id", nullable = false)) })
	public QueryHasPublicationsId getId() {
		return this.id;
	}

	public void setId(QueryHasPublicationsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@ContainedIn
	@JoinColumn(name = "qhb_publication_id", nullable = false, insertable = false, updatable = false)
	public Publications getPublications() {
		return this.publications;
	}

	public void setPublications(Publications publications) {
		this.publications = publications;
	}

	//@Field
	//@FieldBridge(impl = QueriesBridge.class)
	@ManyToOne(fetch = FetchType.LAZY)
	@ContainedIn
	@JoinColumn(name = "qhb_query_id", nullable = false, insertable = false, updatable = false)
	public Queries getQueries() {
		return this.queries;
	}

	public void setQueries(Queries queries) {
		this.queries = queries;
	}

	@Column(name = "qhb_relevance", length = 10)
	public String getQhbRelevance() {
		return this.qhbRelevance;
	}

	public void setQhbRelevance(String qhbRelevance) {
		this.qhbRelevance = qhbRelevance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "queryHasPublications")
	public Set<ClusterLabelPublications> getClusterLabelPublicationses() {
		return this.clusterLabelPublicationses;
	}

	public void setClusterLabelPublicationses(Set<ClusterLabelPublications> clusterLabelPublicationses) {
		this.clusterLabelPublicationses = clusterLabelPublicationses;
	}

}
