package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QueryHasClusterProcesses generated by hbm2java
 */
@Entity
@Table(name = "query_has_cluster_processes")
public class QueryHasClusterProcesses implements java.io.Serializable {

	private QueryHasClusterProcessesId id;
	private ClusterProcesses clusterProcesses;
	private Queries queries;

	public QueryHasClusterProcesses() {
	}

	public QueryHasClusterProcesses(QueryHasClusterProcessesId id, ClusterProcesses clusterProcesses, Queries queries) {
		this.id = id;
		this.clusterProcesses = clusterProcesses;
		this.queries = queries;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "qhcQueryId", column = @Column(name = "qhc_query_id", nullable = false)),
			@AttributeOverride(name = "qhcClusterProcessId", column = @Column(name = "qhc_cluster_process_id", nullable = false)) })
	public QueryHasClusterProcessesId getId() {
		return this.id;
	}

	public void setId(QueryHasClusterProcessesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qhc_cluster_process_id", nullable = false, insertable = false, updatable = false)
	public ClusterProcesses getClusterProcesses() {
		return this.clusterProcesses;
	}

	public void setClusterProcesses(ClusterProcesses clusterProcesses) {
		this.clusterProcesses = clusterProcesses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qhc_query_id", nullable = false, insertable = false, updatable = false)
	public Queries getQueries() {
		return this.queries;
	}

	public void setQueries(Queries queries) {
		this.queries = queries;
	}

}
