package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QueryHasClusterProcessesId generated by hbm2java
 */
@Embeddable
public class QueryHasClusterProcessesId implements java.io.Serializable {

	private long qhcQueryId;
	private long qhcClusterProcessId;

	public QueryHasClusterProcessesId() {
	}

	public QueryHasClusterProcessesId(long qhcQueryId, long qhcClusterProcessId) {
		this.qhcQueryId = qhcQueryId;
		this.qhcClusterProcessId = qhcClusterProcessId;
	}

	@Column(name = "qhc_query_id", nullable = false)
	public long getQhcQueryId() {
		return this.qhcQueryId;
	}

	public void setQhcQueryId(long qhcQueryId) {
		this.qhcQueryId = qhcQueryId;
	}

	@Column(name = "qhc_cluster_process_id", nullable = false)
	public long getQhcClusterProcessId() {
		return this.qhcClusterProcessId;
	}

	public void setQhcClusterProcessId(long qhcClusterProcessId) {
		this.qhcClusterProcessId = qhcClusterProcessId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QueryHasClusterProcessesId))
			return false;
		QueryHasClusterProcessesId castOther = (QueryHasClusterProcessesId) other;

		return (this.getQhcQueryId() == castOther.getQhcQueryId()) && (this.getQhcClusterProcessId() == castOther.getQhcClusterProcessId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQhcQueryId();
		result = 37 * result + (int) this.getQhcClusterProcessId();
		return result;
	}

}
