package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QueryPropertiesId generated by hbm2java
 */
@Embeddable
public class QueryPropertiesId implements java.io.Serializable {

	private long qprQueryId;
	private String qprPropKey;

	public QueryPropertiesId() {
	}

	public QueryPropertiesId(long qprQueryId, String qprPropKey) {
		this.qprQueryId = qprQueryId;
		this.qprPropKey = qprPropKey;
	}

	@Column(name = "qpr_query_id", nullable = false)
	public long getQprQueryId() {
		return this.qprQueryId;
	}

	public void setQprQueryId(long qprQueryId) {
		this.qprQueryId = qprQueryId;
	}

	@Column(name = "qpr_prop_key", nullable = false)
	public String getQprPropKey() {
		return this.qprPropKey;
	}

	public void setQprPropKey(String qprPropKey) {
		this.qprPropKey = qprPropKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QueryPropertiesId))
			return false;
		QueryPropertiesId castOther = (QueryPropertiesId) other;

		return (this.getQprQueryId() == castOther.getQprQueryId())
				&& ((this.getQprPropKey() == castOther.getQprPropKey()) || (this.getQprPropKey() != null && castOther.getQprPropKey() != null && this.getQprPropKey().equals(
						castOther.getQprPropKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQprQueryId();
		result = 37 * result + (getQprPropKey() == null ? 0 : this.getQprPropKey().hashCode());
		return result;
	}

}
