package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourceElementRelations generated by hbm2java
 */
@Entity
@Table(name = "resource_element_relations")
public class ResourceElementRelations implements java.io.Serializable {

	private ResourceElementRelationsId id;
	private ResourceElementRelationTypes resourceElementRelationTypes;
	private ResourceElements resourceElementsByRelResourceElementIdA;
	private ResourceElements resourceElementsByRelResourceElementIdB;

	public ResourceElementRelations() {
	}

	public ResourceElementRelations(ResourceElementRelationsId id, ResourceElementRelationTypes resourceElementRelationTypes,
			ResourceElements resourceElementsByRelResourceElementIdA, ResourceElements resourceElementsByRelResourceElementIdB) {
		this.id = id;
		this.resourceElementRelationTypes = resourceElementRelationTypes;
		this.resourceElementsByRelResourceElementIdA = resourceElementsByRelResourceElementIdA;
		this.resourceElementsByRelResourceElementIdB = resourceElementsByRelResourceElementIdB;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "relResourceElementIdB", column = @Column(name = "rel_resource_element_id_b", nullable = false)),
			@AttributeOverride(name = "relResourceElementIdA", column = @Column(name = "rel_resource_element_id_a", nullable = false)) })
	public ResourceElementRelationsId getId() {
		return this.id;
	}

	public void setId(ResourceElementRelationsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rel_relation_type_id", nullable = false)
	public ResourceElementRelationTypes getResourceElementRelationTypes() {
		return this.resourceElementRelationTypes;
	}

	public void setResourceElementRelationTypes(ResourceElementRelationTypes resourceElementRelationTypes) {
		this.resourceElementRelationTypes = resourceElementRelationTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rel_resource_element_id_a", nullable = false, insertable = false, updatable = false)
	public ResourceElements getResourceElementsByRelResourceElementIdA() {
		return this.resourceElementsByRelResourceElementIdA;
	}

	public void setResourceElementsByRelResourceElementIdA(ResourceElements resourceElementsByRelResourceElementIdA) {
		this.resourceElementsByRelResourceElementIdA = resourceElementsByRelResourceElementIdA;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rel_resource_element_id_b", nullable = false, insertable = false, updatable = false)
	public ResourceElements getResourceElementsByRelResourceElementIdB() {
		return this.resourceElementsByRelResourceElementIdB;
	}

	public void setResourceElementsByRelResourceElementIdB(ResourceElements resourceElementsByRelResourceElementIdB) {
		this.resourceElementsByRelResourceElementIdB = resourceElementsByRelResourceElementIdB;
	}

}
