package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ResourcesTotalElements generated by hbm2java
 */
@Entity
@Table(name = "resources_total_elements")
public class ResourcesTotalElements implements java.io.Serializable {

	private ResourcesTotalElementsId id;

	public ResourcesTotalElements() {
	}

	public ResourcesTotalElements(ResourcesTotalElementsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "resResourceId", column = @Column(name = "res_resource_id", nullable = false)),
			@AttributeOverride(name = "numberElements", column = @Column(name = "numberElements", nullable = false)) })
	public ResourcesTotalElementsId getId() {
		return this.id;
	}

	public void setId(ResourcesTotalElementsId id) {
		this.id = id;
	}

}
