package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourceElementExtenalIdsId generated by hbm2java
 */
@Embeddable
public class ResourceElementExtenalIdsId implements java.io.Serializable {

	private long releResourceElementId;
	private long releSourceId;
	private String releExternalId;

	public ResourceElementExtenalIdsId() {
	}

	public ResourceElementExtenalIdsId(long releResourceElementId, long releSourceId, String releExternalId) {
		this.releResourceElementId = releResourceElementId;
		this.releSourceId = releSourceId;
		this.releExternalId = releExternalId;
	}

	@Column(name = "rele_resource_element_id", nullable = false)
	public long getReleResourceElementId() {
		return this.releResourceElementId;
	}

	public void setReleResourceElementId(long releResourceElementId) {
		this.releResourceElementId = releResourceElementId;
	}

	@Column(name = "rele_source_id", nullable = false)
	public long getReleSourceId() {
		return this.releSourceId;
	}

	public void setReleSourceId(long releSourceId) {
		this.releSourceId = releSourceId;
	}

	@Column(name = "rele_external_id", nullable = false, length = 200)
	public String getReleExternalId() {
		return this.releExternalId;
	}

	public void setReleExternalId(String releExternalId) {
		this.releExternalId = releExternalId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourceElementExtenalIdsId))
			return false;
		ResourceElementExtenalIdsId castOther = (ResourceElementExtenalIdsId) other;

		return (this.getReleResourceElementId() == castOther.getReleResourceElementId())
				&& (this.getReleSourceId() == castOther.getReleSourceId())
				&& ((this.getReleExternalId() == castOther.getReleExternalId()) || (this.getReleExternalId() != null && castOther.getReleExternalId() != null && this
						.getReleExternalId().equals(castOther.getReleExternalId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getReleResourceElementId();
		result = 37 * result + (int) this.getReleSourceId();
		result = 37 * result + (getReleExternalId() == null ? 0 : this.getReleExternalId().hashCode());
		return result;
	}

}
