package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourcesClassSynonymsCountId generated by hbm2java
 */
@Embeddable
public class ResourcesClassSynonymsCountId implements java.io.Serializable {

	private long resResourceId;
	private Long resClassId;
	private long numberSynonyms;

	public ResourcesClassSynonymsCountId() {
	}

	public ResourcesClassSynonymsCountId(long resResourceId, long numberSynonyms) {
		this.resResourceId = resResourceId;
		this.numberSynonyms = numberSynonyms;
	}

	public ResourcesClassSynonymsCountId(long resResourceId, Long resClassId, long numberSynonyms) {
		this.resResourceId = resResourceId;
		this.resClassId = resClassId;
		this.numberSynonyms = numberSynonyms;
	}

	@Column(name = "res_resource_id", nullable = false)
	public long getResResourceId() {
		return this.resResourceId;
	}

	public void setResResourceId(long resResourceId) {
		this.resResourceId = resResourceId;
	}

	@Column(name = "res_class_id")
	public Long getResClassId() {
		return this.resClassId;
	}

	public void setResClassId(Long resClassId) {
		this.resClassId = resClassId;
	}

	@Column(name = "numberSynonyms", nullable = false)
	public long getNumberSynonyms() {
		return this.numberSynonyms;
	}

	public void setNumberSynonyms(long numberSynonyms) {
		this.numberSynonyms = numberSynonyms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesClassSynonymsCountId))
			return false;
		ResourcesClassSynonymsCountId castOther = (ResourcesClassSynonymsCountId) other;

		return (this.getResResourceId() == castOther.getResResourceId())
				&& ((this.getResClassId() == castOther.getResClassId()) || (this.getResClassId() != null && castOther.getResClassId() != null && this.getResClassId().equals(
						castOther.getResClassId()))) && (this.getNumberSynonyms() == castOther.getNumberSynonyms());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResResourceId();
		result = 37 * result + (getResClassId() == null ? 0 : this.getResClassId().hashCode());
		result = 37 * result + (int) this.getNumberSynonyms();
		return result;
	}

}
