package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResourceElements generated by hbm2java
 */
@Entity
@Table(name = "resource_elements")
public class ResourceElements implements java.io.Serializable {

	private long resId;
	private Classes classes;
	private Resources resources;
	private String resElement;
	private Integer resPriorety;
	private boolean resActive;
	private Set<Annotations> annotationses = new HashSet<Annotations>(0);
	private Set<ResourceElementExtenalIds> resourceElementExtenalIdses = new HashSet<ResourceElementExtenalIds>(0);
	private Set<ResourceElementRelations> resourceElementRelationsesForRelResourceElementIdA = new HashSet<ResourceElementRelations>(0);
	private Set<ResourceElementRelations> resourceElementRelationsesForRelResourceElementIdB = new HashSet<ResourceElementRelations>(0);
	private Set<Synonyms> synonymses = new HashSet<Synonyms>(0);

	public ResourceElements() {
	}

	public ResourceElements(long resId, Resources resources, String resElement, boolean resActive) {
		this.resId = resId;
		this.resources = resources;
		this.resElement = resElement;
		this.resActive = resActive;
	}

	public ResourceElements(long resId, Classes classes, Resources resources, String resElement, Integer resPriorety, boolean resActive, Set<Annotations> annotationses,
			Set<ResourceElementExtenalIds> resourceElementExtenalIdses, Set<ResourceElementRelations> resourceElementRelationsesForRelResourceElementIdA,
			Set<ResourceElementRelations> resourceElementRelationsesForRelResourceElementIdB, Set<Synonyms> synonymses) {
		this.resId = resId;
		this.classes = classes;
		this.resources = resources;
		this.resElement = resElement;
		this.resPriorety = resPriorety;
		this.resActive = resActive;
		this.annotationses = annotationses;
		this.resourceElementExtenalIdses = resourceElementExtenalIdses;
		this.resourceElementRelationsesForRelResourceElementIdA = resourceElementRelationsesForRelResourceElementIdA;
		this.resourceElementRelationsesForRelResourceElementIdB = resourceElementRelationsesForRelResourceElementIdB;
		this.synonymses = synonymses;
	}

	@Id
	@Column(name = "res_id", unique = true, nullable = false)
	public long getResId() {
		return this.resId;
	}

	public void setResId(long resId) {
		this.resId = resId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "res_class_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "res_resource_id", nullable = false)
	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	@Column(name = "res_element", nullable = false, length = 500)
	public String getResElement() {
		return this.resElement;
	}

	public void setResElement(String resElement) {
		this.resElement = resElement;
	}

	@Column(name = "res_priorety")
	public Integer getResPriorety() {
		return this.resPriorety;
	}

	public void setResPriorety(Integer resPriorety) {
		this.resPriorety = resPriorety;
	}

	@Column(name = "res_active", nullable = false)
	public boolean isResActive() {
		return this.resActive;
	}

	public void setResActive(boolean resActive) {
		this.resActive = resActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElements")
	public Set<Annotations> getAnnotationses() {
		return this.annotationses;
	}

	public void setAnnotationses(Set<Annotations> annotationses) {
		this.annotationses = annotationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElements")
	public Set<ResourceElementExtenalIds> getResourceElementExtenalIdses() {
		return this.resourceElementExtenalIdses;
	}

	public void setResourceElementExtenalIdses(Set<ResourceElementExtenalIds> resourceElementExtenalIdses) {
		this.resourceElementExtenalIdses = resourceElementExtenalIdses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElementsByRelResourceElementIdA")
	public Set<ResourceElementRelations> getResourceElementRelationsesForRelResourceElementIdA() {
		return this.resourceElementRelationsesForRelResourceElementIdA;
	}

	public void setResourceElementRelationsesForRelResourceElementIdA(Set<ResourceElementRelations> resourceElementRelationsesForRelResourceElementIdA) {
		this.resourceElementRelationsesForRelResourceElementIdA = resourceElementRelationsesForRelResourceElementIdA;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElementsByRelResourceElementIdB")
	public Set<ResourceElementRelations> getResourceElementRelationsesForRelResourceElementIdB() {
		return this.resourceElementRelationsesForRelResourceElementIdB;
	}

	public void setResourceElementRelationsesForRelResourceElementIdB(Set<ResourceElementRelations> resourceElementRelationsesForRelResourceElementIdB) {
		this.resourceElementRelationsesForRelResourceElementIdB = resourceElementRelationsesForRelResourceElementIdB;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElements")
	public Set<Synonyms> getSynonymses() {
		return this.synonymses;
	}

	public void setSynonymses(Set<Synonyms> synonymses) {
		this.synonymses = synonymses;
	}

}
