package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourcesTotalElementsId generated by hbm2java
 */
@Embeddable
public class ResourcesTotalElementsId implements java.io.Serializable {

	private long resResourceId;
	private long numberElements;

	public ResourcesTotalElementsId() {
	}

	public ResourcesTotalElementsId(long resResourceId, long numberElements) {
		this.resResourceId = resResourceId;
		this.numberElements = numberElements;
	}

	@Column(name = "res_resource_id", nullable = false)
	public long getResResourceId() {
		return this.resResourceId;
	}

	public void setResResourceId(long resResourceId) {
		this.resResourceId = resResourceId;
	}

	@Column(name = "numberElements", nullable = false)
	public long getNumberElements() {
		return this.numberElements;
	}

	public void setNumberElements(long numberElements) {
		this.numberElements = numberElements;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesTotalElementsId))
			return false;
		ResourcesTotalElementsId castOther = (ResourcesTotalElementsId) other;

		return (this.getResResourceId() == castOther.getResResourceId()) && (this.getNumberElements() == castOther.getNumberElements());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResResourceId();
		result = 37 * result + (int) this.getNumberElements();
		return result;
	}

}
