package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourcesTotalElementsSynonymsId generated by hbm2java
 */
@Embeddable
public class ResourcesTotalElementsSynonymsId implements java.io.Serializable {

	private long resResourceId;
	private long numberSynonyms;

	public ResourcesTotalElementsSynonymsId() {
	}

	public ResourcesTotalElementsSynonymsId(long resResourceId, long numberSynonyms) {
		this.resResourceId = resResourceId;
		this.numberSynonyms = numberSynonyms;
	}

	@Column(name = "res_resource_id", nullable = false)
	public long getResResourceId() {
		return this.resResourceId;
	}

	public void setResResourceId(long resResourceId) {
		this.resResourceId = resResourceId;
	}

	@Column(name = "numberSynonyms", nullable = false)
	public long getNumberSynonyms() {
		return this.numberSynonyms;
	}

	public void setNumberSynonyms(long numberSynonyms) {
		this.numberSynonyms = numberSynonyms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcesTotalElementsSynonymsId))
			return false;
		ResourcesTotalElementsSynonymsId castOther = (ResourcesTotalElementsSynonymsId) other;

		return (this.getResResourceId() == castOther.getResResourceId()) && (this.getNumberSynonyms() == castOther.getNumberSynonyms());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResResourceId();
		result = 37 * result + (int) this.getNumberSynonyms();
		return result;
	}

}
