package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ResourceElementRelationTypes generated by hbm2java
 */
@Entity
@Table(name = "resource_element_relation_types", uniqueConstraints = @UniqueConstraint(columnNames = "rer_relation_type"))
public class ResourceElementRelationTypes implements java.io.Serializable {

	private long rerId;
	private String rerRelationType;
	private Set<ResourceElementRelations> resourceElementRelationses = new HashSet<ResourceElementRelations>(0);

	public ResourceElementRelationTypes() {
	}

	public ResourceElementRelationTypes(long rerId, String rerRelationType) {
		this.rerId = rerId;
		this.rerRelationType = rerRelationType;
	}

	public ResourceElementRelationTypes(long rerId, String rerRelationType, Set<ResourceElementRelations> resourceElementRelationses) {
		this.rerId = rerId;
		this.rerRelationType = rerRelationType;
		this.resourceElementRelationses = resourceElementRelationses;
	}

	@Id
	@Column(name = "rer_id", unique = true, nullable = false)
	public long getRerId() {
		return this.rerId;
	}

	public void setRerId(long rerId) {
		this.rerId = rerId;
	}

	@Column(name = "rer_relation_type", unique = true, nullable = false)
	public String getRerRelationType() {
		return this.rerRelationType;
	}

	public void setRerRelationType(String rerRelationType) {
		this.rerRelationType = rerRelationType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceElementRelationTypes")
	public Set<ResourceElementRelations> getResourceElementRelationses() {
		return this.resourceElementRelationses;
	}

	public void setResourceElementRelationses(Set<ResourceElementRelations> resourceElementRelationses) {
		this.resourceElementRelationses = resourceElementRelationses;
	}

}
