package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ResourcesTotalElementsSynonyms generated by hbm2java
 */
@Entity
@Table(name = "resources_total_elements_synonyms")
public class ResourcesTotalElementsSynonyms implements java.io.Serializable {

	private ResourcesTotalElementsSynonymsId id;

	public ResourcesTotalElementsSynonyms() {
	}

	public ResourcesTotalElementsSynonyms(ResourcesTotalElementsSynonymsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "resResourceId", column = @Column(name = "res_resource_id", nullable = false)),
			@AttributeOverride(name = "numberSynonyms", column = @Column(name = "numberSynonyms", nullable = false)) })
	public ResourcesTotalElementsSynonymsId getId() {
		return this.id;
	}

	public void setId(ResourcesTotalElementsSynonymsId id) {
		this.id = id;
	}

}
