package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ResourcesClassSynonymsCount generated by hbm2java
 */
@Entity
@Table(name = "resources_class_synonyms_count")
public class ResourcesClassSynonymsCount implements java.io.Serializable {

	private ResourcesClassSynonymsCountId id;

	public ResourcesClassSynonymsCount() {
	}

	public ResourcesClassSynonymsCount(ResourcesClassSynonymsCountId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "resResourceId", column = @Column(name = "res_resource_id", nullable = false)),
			@AttributeOverride(name = "resClassId", column = @Column(name = "res_class_id")),
			@AttributeOverride(name = "numberSynonyms", column = @Column(name = "numberSynonyms", nullable = false)) })
	public ResourcesClassSynonymsCountId getId() {
		return this.id;
	}

	public void setId(ResourcesClassSynonymsCountId id) {
		this.id = id;
	}

}
