package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sources generated by hbm2java
 */
@Entity
@Table(name = "sources", uniqueConstraints = @UniqueConstraint(columnNames = "sou_description"))
public class Sources implements java.io.Serializable {

	private long souId;
	private String souDescription;
	private Set<ResourceElementExtenalIds> resourceElementExtenalIdses = new HashSet<ResourceElementExtenalIds>(0);
	private Set<HyperLinkMenuSourceAssociation> hyperLinkMenuSourceAssociations = new HashSet<HyperLinkMenuSourceAssociation>(0);

	public Sources() {
	}

	public Sources(long souId, String souDescription) {
		this.souId = souId;
		this.souDescription = souDescription;
	}

	public Sources(long souId, String souDescription, Set<ResourceElementExtenalIds> resourceElementExtenalIdses,
			Set<HyperLinkMenuSourceAssociation> hyperLinkMenuSourceAssociations) {
		this.souId = souId;
		this.souDescription = souDescription;
		this.resourceElementExtenalIdses = resourceElementExtenalIdses;
		this.hyperLinkMenuSourceAssociations = hyperLinkMenuSourceAssociations;
	}

	@Id
	@Column(name = "sou_id", unique = true, nullable = false)
	public long getSouId() {
		return this.souId;
	}

	public void setSouId(long souId) {
		this.souId = souId;
	}

	@Column(name = "sou_description", unique = true, nullable = false)
	public String getSouDescription() {
		return this.souDescription;
	}

	public void setSouDescription(String souDescription) {
		this.souDescription = souDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sources")
	public Set<ResourceElementExtenalIds> getResourceElementExtenalIdses() {
		return this.resourceElementExtenalIdses;
	}

	public void setResourceElementExtenalIdses(Set<ResourceElementExtenalIds> resourceElementExtenalIdses) {
		this.resourceElementExtenalIdses = resourceElementExtenalIdses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sources")
	public Set<HyperLinkMenuSourceAssociation> getHyperLinkMenuSourceAssociations() {
		return this.hyperLinkMenuSourceAssociations;
	}

	public void setHyperLinkMenuSourceAssociations(Set<HyperLinkMenuSourceAssociation> hyperLinkMenuSourceAssociations) {
		this.hyperLinkMenuSourceAssociations = hyperLinkMenuSourceAssociations;
	}

}
