package com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.model.core.entities;

// Generated 23/Mar/2015 16:36:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.FieldBridge;
import org.hibernate.search.annotations.IndexedEmbedded;

import com.silicolife.textmining.core.datastructures.dataaccess.database.dataaccess.implementation.lucene.bridges.SynonymsIdBridge;

/**
 * Synonyms generated by hbm2java
 */
@Entity
@Table(name = "synonyms")
public class Synonyms implements java.io.Serializable {

	private SynonymsId id;
	private ResourceElements resourceElements;

	public Synonyms() {
	}

	public Synonyms(SynonymsId id, ResourceElements resourceElements) {
		this.id = id;
		this.resourceElements = resourceElements;
	}

	@EmbeddedId
	@DocumentId
	@FieldBridge(impl = SynonymsIdBridge.class)
	@IndexedEmbedded
	@AttributeOverrides({ @AttributeOverride(name = "synResourceElementId", column = @Column(name = "syn_resource_element_id", nullable = false)),
			@AttributeOverride(name = "synSynonym", column = @Column(name = "syn_synonym", nullable = false, length = 500)),
			@AttributeOverride(name = "synActive", column = @Column(name = "syn_active", nullable = false)) })
	public SynonymsId getId() {
		return this.id;
	}

	public void setId(SynonymsId id) {
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@ContainedIn
	@JoinColumn(name = "syn_resource_element_id", nullable = false, insertable = false, updatable = false)
	public ResourceElements getResourceElements() {
		return this.resourceElements;
	}

	public void setResourceElements(ResourceElements resourceElements) {
		this.resourceElements = resourceElements;
	}

}
